pitchparser:	pitchparser.l
			/opt/local/bin/bison --version
			/opt/local/bin/flex --version
			/opt/local/bin/flex -o pitchparser.c pitchparser.l
			
clean:		
			rm -f pitchparser.c
			rm -f pitchparser.tab.c
			rm -f pitchparser.tab.h
			rm -f pitchparser.lex.h