
# Add  switches for Easdif
INCLUDE(UsePkgConfig)
PKGCONFIG(libEasdif${DEBUGEXT}     EASDIF_INC_DIR LIBEASDIF${DEBUGEXT}_LINK_DIR LIBEASDIF_LINK_FLAGS LIBEASDIF_CFLAGS)

IF(NOT EASDIF_LIB${DEBUGEXT})
  FIND_LIBRARY(EASDIF_LIB${DEBUGEXT} Names Easdif${DEBUGEXT}  PATHS  ${LIBRARY_OUTPUT_PATH} ${CMAKE_INSTALL_PREFIX}/${INSTALL_LIB_DIR} ${LIBEASDIF${DEBUGEXT}_LINK_DIR} /u/formes/share/lib/$ENV{SYS}   /usr/local/lib /usr/lib  DOC "Path to EaSDIF library")
ENDIF(NOT EASDIF_LIB${DEBUGEXT})


IF(NOT EASDIF_INC_DIR)
  FIND_PATH(EASDIF_INC_DIR easdif/easdif.h  ${CMAKE_BINARY_DIR}/include ${CMAKE_INSTALL_PREFIX}/${INSTALL_INC_DIR} /u/formes/share/include   /usr/local/include /usr/include  DOC "Path to EaSDIF includes")
ENDIF(NOT EASDIF_INC_DIR)

INCLUDE_DIRECTORIES(${EASDIF_INC_DIR})
