chkparser:	chkparser.l
			/opt/local/bin/flex --version
			/opt/local/bin/flex -o chkparser.c chkparser.l 
			
						
clean:		
			rm -f chkparser.c
			rm -f chkparser.tab.c
			rm -f chkparser.tab.h
			