alterparser:	alterparser.l
			/opt/local/bin/bison --version
			/opt/local/bin/flex --version
			/opt/local/bin/flex -o alterparser.c alterparser.l
			
clean:		
			rm -f alterparser.c
			rm -f alterparser.tab.c
			rm -f alterparser.tab.h
			rm -f alterparser.lex.h