MACRO(CREATE_CVSTAG_TARGET VERSION_TAG)
IF(NOT CREATE_CVSTAG_TARGET_INIT)
  # create cvstags for current version
  ADD_CUSTOM_TARGET(cvstags 
    COMMAND cd ${CMAKE_CURRENT_SOURCE_DIR}\; cvs tag  -F ${VERSION_TAG}\; echo "tag ${VERSION_TAG} set")
  SET(CREATE_CVSTAG_TARGET_INIT 1)
ENDIF(NOT CREATE_CVSTAG_TARGET_INIT)
ENDMACRO(CREATE_CVSTAG_TARGET VERSION_TAG)
