
#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define strparser__create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer strparser__create_buffer
#endif

#ifdef yy_delete_buffer
#define strparser__delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer strparser__delete_buffer
#endif

#ifdef yy_scan_buffer
#define strparser__scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer strparser__scan_buffer
#endif

#ifdef yy_scan_string
#define strparser__scan_string_ALREADY_DEFINED
#else
#define yy_scan_string strparser__scan_string
#endif

#ifdef yy_scan_bytes
#define strparser__scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes strparser__scan_bytes
#endif

#ifdef yy_init_buffer
#define strparser__init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer strparser__init_buffer
#endif

#ifdef yy_flush_buffer
#define strparser__flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer strparser__flush_buffer
#endif

#ifdef yy_load_buffer_state
#define strparser__load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state strparser__load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define strparser__switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer strparser__switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define strparser_push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state strparser_push_buffer_state
#endif

#ifdef yypop_buffer_state
#define strparser_pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state strparser_pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define strparser_ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack strparser_ensure_buffer_stack
#endif

#ifdef yylex
#define strparser_lex_ALREADY_DEFINED
#else
#define yylex strparser_lex
#endif

#ifdef yyrestart
#define strparser_restart_ALREADY_DEFINED
#else
#define yyrestart strparser_restart
#endif

#ifdef yylex_init
#define strparser_lex_init_ALREADY_DEFINED
#else
#define yylex_init strparser_lex_init
#endif

#ifdef yylex_init_extra
#define strparser_lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra strparser_lex_init_extra
#endif

#ifdef yylex_destroy
#define strparser_lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy strparser_lex_destroy
#endif

#ifdef yyget_debug
#define strparser_get_debug_ALREADY_DEFINED
#else
#define yyget_debug strparser_get_debug
#endif

#ifdef yyset_debug
#define strparser_set_debug_ALREADY_DEFINED
#else
#define yyset_debug strparser_set_debug
#endif

#ifdef yyget_extra
#define strparser_get_extra_ALREADY_DEFINED
#else
#define yyget_extra strparser_get_extra
#endif

#ifdef yyset_extra
#define strparser_set_extra_ALREADY_DEFINED
#else
#define yyset_extra strparser_set_extra
#endif

#ifdef yyget_in
#define strparser_get_in_ALREADY_DEFINED
#else
#define yyget_in strparser_get_in
#endif

#ifdef yyset_in
#define strparser_set_in_ALREADY_DEFINED
#else
#define yyset_in strparser_set_in
#endif

#ifdef yyget_out
#define strparser_get_out_ALREADY_DEFINED
#else
#define yyget_out strparser_get_out
#endif

#ifdef yyset_out
#define strparser_set_out_ALREADY_DEFINED
#else
#define yyset_out strparser_set_out
#endif

#ifdef yyget_leng
#define strparser_get_leng_ALREADY_DEFINED
#else
#define yyget_leng strparser_get_leng
#endif

#ifdef yyget_text
#define strparser_get_text_ALREADY_DEFINED
#else
#define yyget_text strparser_get_text
#endif

#ifdef yyget_lineno
#define strparser_get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno strparser_get_lineno
#endif

#ifdef yyset_lineno
#define strparser_set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno strparser_set_lineno
#endif

#ifdef yyget_column
#define strparser_get_column_ALREADY_DEFINED
#else
#define yyget_column strparser_get_column
#endif

#ifdef yyset_column
#define strparser_set_column_ALREADY_DEFINED
#else
#define yyset_column strparser_set_column
#endif

#ifdef yywrap
#define strparser_wrap_ALREADY_DEFINED
#else
#define yywrap strparser_wrap
#endif

#ifdef yyget_lval
#define strparser_get_lval_ALREADY_DEFINED
#else
#define yyget_lval strparser_get_lval
#endif

#ifdef yyset_lval
#define strparser_set_lval_ALREADY_DEFINED
#else
#define yyset_lval strparser_set_lval
#endif

#ifdef yyalloc
#define strparser_alloc_ALREADY_DEFINED
#else
#define yyalloc strparser_alloc
#endif

#ifdef yyrealloc
#define strparser_realloc_ALREADY_DEFINED
#else
#define yyrealloc strparser_realloc
#endif

#ifdef yyfree
#define strparser_free_ALREADY_DEFINED
#else
#define yyfree strparser_free
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define strparser_wrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 22
#define YY_END_OF_BUFFER 23
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[445] =
    {   0,
       18,   18,   20,   20,   18,   18,   20,   20,   18,   18,
       20,   20,   18,   18,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   18,   18,   20,   20,   18,   18,   20,   20,
       18,   18,   20,   20,   18,   18,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   18,   18,   20,   20,   18,   18,
       20,   20,   18,   18,   20,   20,   18,   18,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   18,   18,   20,   20,

       18,   18,   20,   20,   18,   18,   20,   20,   18,   18,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   18,   18,
       20,   20,   18,   18,   20,   20,   18,   18,   20,   20,
       18,   18,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       18,   18,   20,   20,   18,   18,   20,   20,   18,   18,
       20,   20,   18,   18,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   18,   18,   20,   20,   18,   18,   20,   20,

       18,   18,   20,   20,   18,   18,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   18,   18,   20,   20,   18,   18,
       20,   20,   18,   18,   20,   20,   18,   18,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   23,   18,   17,   18,
        1,    2,   18,   18,    3,   18,    1,   19,    2,   11,
       18,   20,   20,   20,   20,    3,   20,   21,   11,   20,
       18,   18,   18,    3,   20,   20,   20,    3,    1,    2,
       18,   20,   18,   18,   20,   20,   18,    3,   20,    3,

       18,   18,    3,   20,   20,    3,   18,   20,   18,   18,
       20,   20,   18,   19,   18,    0,   13,   19,   18,    3,
       18,    5,    5,   18,   18,   18,   18,    7,   19,   19,
       19,   11,   11,   12,   18,   18,   20,   21,   20,   13,
       21,   20,    3,   20,    5,    5,   20,   20,   20,   20,
        7,   21,   21,   21,   11,   12,   20,   20,    3,   18,
        3,    6,    6,    3,   20,    3,    6,    6,    3,    3,
        3,    3,    3,    3,   13,    0,   19,   19,   14,    0,
       19,   18,   18,    4,   18,    5,   18,    7,    8,   18,
       12,   12,   12,   12,   12,   16,   18,   21,   21,   14,

       21,   20,   20,    4,   20,    5,   20,    7,    8,   20,
       12,   12,   12,   16,   20,   14,    0,   19,    0,   14,
       14,   18,    5,   18,   12,   12,   15,   21,   14,   20,
        5,   20,   15,   18,    9,   20,    9,   18,   18,   20,
       20,   10,   10,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    6,
        7,    1,    8,    1,    9,   10,   11,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    1,    1,    1,
        1,    1,    1,    1,   13,   13,   13,   13,   14,   13,
       13,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       15,   16,   17,    5,    1,   18,   19,   20,   19,   20,

       21,   19,   19,    1,   22,    1,    1,   23,    1,   24,
        1,    1,    5,    1,    1,   25,   26,    5,    1,    5,
        1,    1,    1,   27,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[28] =
    {   0,
        1,    2,    2,    1,    1,    3,    3,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[469] =
    {   0,
        0,    0,   27,    0,  919,  912,  911,  905,   47,   52,
       57,   62,   67,   78,   89,  100,   74,   77,    0,    0,
      113,  126,  869,  864,  139,    0,   96,   99,  857,  850,
      151,  164,  175,    0,  189,    0,  838,  835,  826,  820,
      113,  126,  151,  164,  203,  214,  225,  236,  184,  199,
        0,    0,  249,  262,  818,  809,  273,    0,  219,  230,
      803,  287,  243,  246,  262,  264,  276,  290,  301,  303,
      308,  315,  320,  326,  331,  336,  341,  352,  363,  374,
      346,  357,  368,  379,  385,  396,  401,  403,  390,  408,
      414,  419,  424,  426,  437,  448,  431,  442,  453,  455,

      460,  462,  467,  474,  479,  485,  490,  495,  500,  511,
      522,  533,  505,  516,  527,  538,  544,  549,  554,  556,
      561,  567,  572,  577,  582,  584,  589,  600,  778,  776,
      752,  746,  162,  169,  611,    0,  628,  645,  662,  673,
      684,    0,  594,  605,  703,  716,  743,  729,  627,  641,
        0,    0,  713,  700,  729,  748,  201,  212,  651,  656,
      680,  665,  660,  654,  223,  233,  241,  265,  765,  782,
      799,  816,  833,    0,  852,  871,  890,  909,  649,  643,
      926,  943,  273,  307,  638,  339,  962,  979,  619,  603,
      998, 1017,  689,  691,  720,  731,  667,  678,  614,  637,

      733,  748, 1034, 1045,  718,  750,  759,  770, 1056, 1073,
      775,  787, 1090,    0,  789,  804,  806,  823, 1107, 1118,
      840,  852,  862,  871,  882, 1129,  901,  919,  890,  909,
     1140, 1157,  936,  948, 1174, 1191,  825,  950, 1208,    0,
     1225, 1242,  699,  848,  598,  593,  962,  972,  984,  989,
      587,  582,  886,  905,    0,    0,  583,  544, 1578, 1265,
     1578, 1578, 1272,   66, 1284, 1301,  539,  124,  533,  146,
      352,  522, 1004, 1312,   88, 1324, 1341,  162,  511,  363,
       83,  105,  188,  930,  127,  165,  302, 1000,  506,  500,
     1009, 1017,  384, 1035,  425, 1046,  499,  206,  494,  292,

      629,  707, 1057,  738,  776, 1060, 1074, 1077,  436, 1091,
      461, 1094,  485,  709, 1360,  151,  474, 1375,  521,    0,
        0, 1014, 1097, 1134, 1145, 1028,  532, 1387,  465,  443,
      801,  813,  437, 1413,  169,  402,  414,  962, 1075,  391,
     1118,  555,    0,    0, 1119, 1156, 1147, 1179, 1181,  769,
     1425,  385,  374, 1015,  336, 1058,  572,  605,  873,  892,
     1194, 1059, 1076, 1162, 1155, 1197, 1164, 1180,  566,  639,
     1207, 1212, 1209, 1226, 1578,  274, 1451, 1466,    0,  480,
     1481, 1231, 1215, 1229, 1232, 1241, 1243,  927, 1257, 1249,
     1273,  969, 1032,  331, 1496,  326,  823, 1299, 1339, 1356,

     1367, 1271, 1258, 1292, 1295, 1300, 1302, 1332, 1368, 1307,
      321,  306, 1383,  259,  850,  691,  748,    0,  806,  246,
     1578, 1335, 1377, 1386,  204, 1401,  191, 1406,  134, 1378,
     1389, 1412,  126, 1423,  113, 1432,  108, 1409, 1426, 1431,
     1434,   57,   52, 1578,   62, 1512, 1515, 1517, 1520, 1523,
     1526, 1529, 1532, 1535,   57, 1538, 1541, 1544, 1547, 1550,
     1553, 1556, 1559, 1562, 1565, 1568, 1571, 1574
    } ;

static const flex_int16_t yy_def[469] =
    {   0,
      444,    1,  444,    3,    1,    1,    3,    3,    1,    1,
        3,    3,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,   25,   25,   25,   25,   25,
       25,   25,    1,   33,    3,   35,   33,   33,   35,   35,
       33,   33,   35,   35,   33,   33,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   25,   57,   35,   35,
       57,   25,   62,   62,    1,    1,    3,    3,    1,    1,
        3,    3,    1,    1,    3,    3,    1,    1,    3,    3,
       25,   25,    3,    3,   25,   25,    3,    3,   25,   25,
        3,    3,   25,   25,    3,    3,   33,   33,   35,   35,

       33,   33,   35,   35,   33,   33,   35,   35,   33,   33,
       35,   35,   57,   57,   35,   35,   62,   62,   35,   35,
       57,   57,   35,   35,   62,   62,   35,   35,    1,    1,
        3,    3,    1,    1,   35,  135,    1,    1,  135,  135,
        1,  141,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,   25,   25,   25,   25,   25,   25,  135,  135,
       33,   33,   35,   35,   33,   33,   35,   35,   33,   33,
       35,   35,   33,  173,   62,   62,   35,   35,   35,   35,
       62,   62,   35,   35,   57,   62,   57,   35,   62,   62,
       62,   62,    1,    1,  135,  135,  141,  141,  135,  135,

      141,  141,  135,  135,  141,  141,  135,  135,   25,   25,
      135,  135,   25,  213,  135,  135,   25,   25,  135,  135,
      213,  213,  135,  135,   33,  173,   35,   35,  173,  173,
       35,   35,  173,  173,   35,   35,  173,  173,   35,  239,
       57,   62,  242,  242,  242,  242,  239,  239,  242,  242,
      239,  239,  239,  239,  239,  239,  444,  445,  444,  446,
      444,  444,  445,  445,  445,  445,  445,  447,  445,  448,
      445,  449,  450,  449,  449,  449,  449,  451,  452,  449,
      263,  263,  445,  445,  274,  274,  449,  449,  449,  449,
      445,  449,  445,  445,  449,  449,  263,  265,  274,  276,

      263,  263,  445,  274,  274,  449,  445,  449,  445,  445,
      449,  449,  445,  447,  446,  453,  445,  454,  445,  265,
      266,  445,  445,  445,  445,  266,  445,  266,  455,  455,
      447,  448,  456,  457,  445,  445,  449,  451,  450,  449,
      458,  449,  276,  277,  449,  449,  449,  449,  277,  449,
      277,  459,  459,  451,  452,  460,  449,  449,  445,  445,
      445,  445,  445,  449,  449,  449,  449,  449,  265,  276,
      445,  445,  449,  449,  444,  461,  462,  462,  378,  463,
      454,  445,  445,  445,  445,  445,  445,  328,  445,  445,
      464,  465,  465,  466,  457,  445,  445,  467,  467,  467,

      458,  449,  449,  449,  449,  449,  449,  351,  449,  449,
      468,  468,  460,  449,  449,  463,  461,  378,  463,  455,
      444,  445,  445,  445,  466,  464,  445,  467,  459,  449,
      449,  449,  449,  445,  445,  449,  449,  445,  445,  449,
      449,  445,  449,    0,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444
    } ;

static const flex_int16_t yy_nxt[1606] =
    {   0,
      258,  259,  259,  260,  258,  261,  262,  263,  263,  264,
      258,  265,  266,  266,  267,  268,  269,  270,  266,  266,
      266,  258,  258,  271,  258,  258,  258,  272,  259,  259,
      273,  272,  272,  272,  274,  274,  275,  272,  276,  277,
      277,  272,  278,  272,  279,  277,  277,  277,  272,  272,
      280,  272,  272,  272,  281,  282,  283,  330,  284,  281,
      282,  283,  313,  284,  285,  286,  287,  338,  288,  285,
      286,  287,  314,  288,  281,  282,  283,  322,  284,  289,
      290,  314,  289,  290,  258,  281,  282,  283,  289,  284,
      290,  289,  313,  290,  359,  258,  285,  286,  287,  345,

      288,  272,  272,  338,  272,  272,  272,  285,  286,  287,
      272,  288,  272,  272,  360,  272,  361,  272,  289,  290,
      293,  294,  283,  338,  284,  330,  330,  289,  314,  290,
      272,  289,  290,  293,  294,  283,  337,  284,  364,  331,
      289,  338,  290,  272,  289,  290,  285,  286,  287,  338,
      288,  333,  333,  289,  375,  290,  272,  272,  295,  296,
      287,  334,  288,  353,  353,  272,  376,  272,  272,  272,
      272,  295,  296,  287,  365,  288,  366,  354,  272,  258,
      272,  272,  291,  291,  314,  258,  258,  258,  258,  289,
      290,  396,  258,  258,  258,  258,  292,  292,  289,  362,

      290,  272,  272,  314,  289,  290,  314,  272,  272,  272,
      293,  294,  283,  289,  284,  290,  313,  369,  272,  391,
      258,  293,  294,  283,  272,  284,  295,  296,  287,  272,
      288,  258,  295,  296,  287,  272,  288,  295,  296,  287,
      258,  288,  272,  295,  296,  287,  258,  288,  272,  272,
      258,  272,  272,  272,  289,  290,  258,  272,  272,  272,
      272,  314,  272,  289,  272,  290,  272,  289,  290,  297,
      297,  297,  297,  298,  338,  298,  289,  416,  290,  272,
      295,  296,  272,  299,  299,  272,  272,  300,  272,  417,
      272,  272,  272,  272,  295,  296,  272,  299,  299,  272,

      272,  300,  337,  370,  272,  272,  272,  272,  297,  297,
      297,  297,  298,  367,  298,  299,  299,  338,  258,  300,
      258,  356,  299,  299,  272,  272,  300,  301,  302,  283,
      272,  303,  272,  301,  302,  283,  356,  303,  304,  305,
      287,  314,  306,  304,  305,  287,  391,  306,  301,  302,
      283,  356,  303,  299,  299,  275,  279,  300,  258,  301,
      302,  283,  272,  303,  299,  299,  275,  314,  300,  258,
      304,  305,  287,  335,  306,  299,  299,  336,  338,  300,
      272,  304,  305,  287,  357,  306,  299,  299,  358,  338,
      300,  272,  299,  299,  275,  359,  300,  304,  305,  314,

      338,  306,  272,  299,  299,  275,  338,  300,  299,  299,
      299,  299,  300,  272,  300,  304,  305,  314,  272,  306,
      272,  304,  305,  287,  397,  306,  304,  305,  287,  338,
      306,  304,  305,  304,  305,  306,  364,  306,  307,  307,
      338,  272,  298,  272,  304,  305,  287,  371,  306,  307,
      307,  314,  391,  298,  272,  304,  305,  287,  314,  306,
      308,  308,  308,  308,  300,  272,  300,  307,  307,  307,
      307,  298,  373,  298,  308,  308,  338,  258,  300,  258,
      314,  308,  308,  421,  272,  300,  309,  310,  283,  314,
      303,  272,  309,  310,  283,  376,  303,  311,  312,  287,

      314,  306,  311,  312,  287,  370,  306,  309,  310,  283,
      369,  303,  308,  308,  275,  338,  300,  258,  309,  310,
      283,  338,  303,  308,  308,  275,  356,  300,  258,  311,
      312,  287,  322,  306,  308,  308,  314,  338,  300,  272,
      311,  312,  287,  328,  306,  308,  308,  314,  314,  300,
      272,  308,  308,  275,  314,  300,  308,  308,  275,  314,
      300,  308,  308,  308,  308,  300,  345,  300,  311,  312,
      338,  272,  306,  272,  311,  312,  313,  369,  306,  311,
      312,  287,  444,  306,  311,  312,  287,  338,  306,  311,
      312,  311,  312,  306,  414,  306,  311,  312,  287,  279,

      306,  285,  286,  287,  279,  288,  272,  311,  312,  287,
      272,  306,  285,  286,  287,  272,  288,  272,  274,  274,
      338,  299,  299,  277,  277,  300,  272,  415,  272,  277,
      277,  277,  289,  290,  272,  281,  282,  283,  313,  284,
      371,  289,  272,  290,  299,  299,  289,  290,  300,  337,
      370,  258,  281,  282,  283,  289,  284,  290,  285,  286,
      287,  272,  288,  285,  286,  287,  272,  288,  258,  285,
      286,  287,  272,  288,  297,  297,  264,  272,  298,  279,
      285,  286,  287,  272,  288,  297,  297,  264,  258,  298,
      279,  281,  282,  283,  421,  284,  297,  297,  297,  297,

      298,  258,  298,  258,  272,  272,  376,  258,  289,  290,
      330,  330,  258,  272,  258,  272,  360,  289,  372,  290,
      279,  289,  290,  272,  331,  301,  302,  299,  299,  303,
      289,  300,  290,  279,  272,  272,  272,  279,  299,  299,
      301,  302,  300,  272,  303,  272,  279,  337,  279,  373,
      270,  416,  272,  272,  272,  301,  302,  301,  302,  303,
      279,  303,  272,  417,  272,  270,  304,  305,  287,  272,
      306,  272,  293,  294,  283,  272,  284,  304,  305,  287,
      351,  306,  299,  299,  338,  365,  300,  374,  258,  293,
      294,  283,  279,  284,  299,  299,  299,  299,  300,  258,

      300,  258,  330,  330,  279,  258,  295,  296,  287,  421,
      288,  299,  299,  304,  305,  300,  331,  306,  333,  333,
      272,  376,  272,  295,  296,  287,  272,  288,  334,  272,
      304,  305,  309,  310,  306,  272,  303,  272,  314,  272,
      293,  294,  283,  272,  284,  427,  272,  304,  305,  287,
      258,  306,  258,  272,  272,  258,  258,  272,  272,  304,
      305,  287,  272,  306,  272,  338,  272,  272,  272,  304,
      305,  287,  433,  306,  272,  272,  272,  272,  304,  305,
      287,  272,  306,  324,  359,  272,  272,  272,  314,  307,
      307,  289,  290,  298,  272,  289,  290,  307,  307,  264,

      289,  298,  290,  362,  289,  258,  290,  314,  308,  308,
      289,  290,  300,  272,  289,  290,  307,  307,  264,  289,
      298,  290,  272,  289,  272,  290,  308,  308,  272,  258,
      300,  313,  272,  292,  292,  275,  258,  276,  388,  363,
      324,  361,  272,  309,  310,  314,  313,  303,  444,  272,
      292,  292,  275,  270,  276,  309,  310,  309,  310,  303,
      444,  303,  444,  353,  353,  270,  272,  272,  272,  308,
      308,  275,  444,  300,  425,  425,  272,  354,  272,  308,
      308,  275,  444,  300,  334,  272,  295,  296,  287,  444,
      288,  311,  312,  287,  444,  306,  311,  312,  287,  444,

      306,  444,  272,  272,  272,  316,  316,  340,  444,  368,
      347,  366,  272,  444,  272,  338,  353,  353,  319,  341,
      320,  272,  272,  272,  314,  322,  342,  382,  343,  314,
      354,  272,  338,  272,  382,  387,  387,  425,  425,  388,
      272,  304,  305,  287,  360,  306,  361,  334,  444,  444,
      314,  279,  304,  305,  287,  365,  306,  366,  444,  412,
      412,  338,  279,  299,  299,  275,  363,  300,  372,  368,
      362,  374,  314,  413,  314,  338,  316,  316,  340,  272,
      299,  299,  275,  319,  300,  369,  342,  362,  370,  314,
      341,  314,  338,  444,  444,  444,  272,  299,  299,  275,

      360,  300,  372,  365,  444,  374,  314,  272,  322,  338,
      382,  444,  314,  272,  304,  305,  287,  382,  306,  399,
      399,  400,  444,  444,  279,  304,  305,  287,  444,  306,
      345,  444,  402,  401,  338,  279,  307,  307,  264,  402,
      298,  383,  383,  444,  444,  384,  270,  308,  308,  314,
      444,  300,  385,  385,  403,  403,  386,  272,  404,  444,
      314,  444,  338,  272,  308,  308,  367,  345,  300,  402,
      338,  338,  347,  364,  272,  367,  402,  338,  444,  338,
      272,  311,  312,  287,  444,  306,  405,  405,  407,  407,
      406,  367,  408,  444,  338,  338,  444,  272,  311,  312,

      287,  444,  306,  363,  324,  361,  368,  347,  366,  314,
      444,  444,  338,  444,  272,  311,  312,  287,  371,  306,
      373,  363,  314,  372,  338,  272,  384,  314,  444,  444,
      314,  272,  308,  308,  275,  368,  300,  374,  422,  422,
      384,  338,  423,  386,  314,  444,  314,  314,  272,  308,
      308,  275,  386,  300,  388,  444,  314,  444,  314,  279,
      424,  389,  444,  444,  314,  272,  316,  316,  317,  404,
      316,  316,  314,  338,  425,  425,  389,  444,  430,  430,
      318,  319,  431,  320,  321,  321,  338,  314,  426,  444,
      321,  321,  321,  323,  324,  320,  444,  325,  444,  314,

      419,  419,  429,  404,  325,  326,  406,  338,  327,  327,
      338,  406,  328,  408,  341,  338,  314,  338,  432,  444,
      326,  342,  338,  343,  344,  344,  444,  338,  444,  444,
      344,  344,  344,  346,  347,  343,  337,  348,  444,  338,
      419,  419,  429,  408,  348,  349,  423,  444,  350,  350,
      314,  337,  351,  444,  341,  444,  338,  419,  419,  429,
      349,  316,  316,  317,  444,  316,  316,  444,  399,  399,
      400,  341,  409,  444,  444,  318,  378,  378,  379,  444,
      380,  380,  401,  338,  412,  412,  444,  409,  423,  431,
      381,  389,  314,  338,  390,  390,  434,  424,  413,  444,

      431,  314,  425,  425,  338,  444,  389,  419,  419,  429,
      435,  444,  444,  390,  393,  393,  426,  444,  394,  394,
      439,  341,  436,  432,  314,  444,  444,  338,  395,  409,
      438,  438,  410,  410,  439,  444,  437,  439,  314,  440,
      440,  314,  441,  441,  409,  441,  338,  338,  444,  338,
      442,  410,  419,  419,  420,  444,  419,  419,  443,  444,
      444,  444,  444,  444,  444,  444,  318,  419,  419,  420,
      444,  419,  419,  444,  444,  444,  444,  444,  444,  444,
      444,  318,  378,  378,  379,  444,  380,  380,  444,  444,
      444,  444,  444,  444,  444,  444,  381,  393,  393,  444,

      444,  394,  394,  444,  444,  444,  444,  444,  444,  444,
      444,  395,  315,  315,  315,  329,  329,  332,  444,  332,
      337,  444,  337,  339,  339,  339,  352,  352,  352,  355,
      444,  355,  316,  316,  316,  377,  377,  377,  333,  444,
      333,  392,  392,  392,  398,  398,  398,  353,  444,  353,
      411,  411,  411,  380,  380,  380,  418,  418,  418,  419,
      419,  419,  394,  394,  394,  393,  444,  393,  425,  444,
      425,  428,  428,  428,  412,  444,  412,  257,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,

      444,  444,  444,  444,  444
    } ;

static const flex_int16_t yy_chk[1606] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    9,    9,    9,  455,    9,   10,
       10,   10,  445,   10,   11,   11,   11,  443,   11,   12,
       12,   12,  442,   12,   13,   13,   13,  264,   13,   17,
       17,  264,   18,   18,   13,   14,   14,   14,   17,   14,
       17,   18,  281,   18,  281,   14,   15,   15,   15,  275,

       15,   27,   27,  275,   28,   28,   15,   16,   16,   16,
       27,   16,   27,   28,  282,   28,  282,   16,   21,   21,
       41,   41,   41,  437,   41,  268,  268,   21,  435,   21,
       21,   22,   22,   42,   42,   42,  285,   42,  285,  268,
       22,  433,   22,   22,   25,   25,   25,   25,   25,  429,
       25,  270,  270,   25,  316,   25,   31,   31,   43,   43,
       43,  270,   43,  278,  278,   31,  316,   31,   31,   32,
       32,   44,   44,   44,  286,   44,  286,  278,   32,  133,
       32,   32,   33,   33,  335,  133,  134,   33,   33,   49,
       49,  335,  134,   33,   33,   33,   35,   35,   49,  283,

       49,   35,   35,  283,   50,   50,  427,   35,   35,   35,
       45,   45,   45,   50,   45,   50,  298,  298,  157,  425,
       45,   46,   46,   46,  157,   46,   59,   59,   59,  158,
       59,   46,   47,   47,   47,  158,   47,   60,   60,   60,
      165,   60,   47,   48,   48,   48,  165,   48,   63,   63,
      166,   64,   64,   48,   53,   53,  166,   63,  167,   63,
       64,  420,   64,   53,  167,   53,   53,   54,   54,   65,
       65,   66,   66,   65,  414,   66,   54,  376,   54,   54,
       57,   57,  168,   67,   67,   57,   57,   67,  168,  376,
      183,   57,   57,   57,   62,   62,  183,   68,   68,   62,

       62,   68,  300,  300,   62,   62,   62,   62,   69,   69,
       70,   70,   69,  287,   70,   71,   71,  287,   69,   71,
       70,  412,   72,   72,  184,   71,   72,   73,   73,   73,
      184,   73,   72,   74,   74,   74,  411,   74,   75,   75,
       75,  396,   75,   76,   76,   76,  394,   76,   77,   77,
       77,  355,   77,   81,   81,   81,  186,   81,   77,   78,
       78,   78,  186,   78,   82,   82,   82,  271,   82,   78,
       79,   79,   79,  271,   79,   83,   83,  271,  280,   83,
       79,   80,   80,   80,  280,   80,   84,   84,  280,  353,
       84,   80,   85,   85,   85,  293,   85,   89,   89,  293,

      352,   89,   85,   86,   86,   86,  340,   86,   87,   87,
       88,   88,   87,   86,   88,   90,   90,  336,   87,   90,
       88,   91,   91,   91,  336,   91,   92,   92,   92,  337,
       92,   93,   93,   94,   94,   93,  295,   94,   97,   97,
      295,   93,   97,   94,   95,   95,   95,  309,   95,   98,
       98,  309,  333,   98,   95,   96,   96,   96,  330,   96,
       99,   99,  100,  100,   99,   96,  100,  101,  101,  102,
      102,  101,  311,  102,  103,  103,  311,  101,  103,  102,
      329,  104,  104,  380,  103,  104,  105,  105,  105,  317,
      105,  104,  106,  106,  106,  380,  106,  107,  107,  107,

      313,  107,  108,  108,  108,  299,  108,  109,  109,  109,
      297,  109,  113,  113,  113,  290,  113,  109,  110,  110,
      110,  289,  110,  114,  114,  114,  279,  114,  110,  111,
      111,  111,  319,  111,  115,  115,  319,  272,  115,  111,
      112,  112,  112,  327,  112,  116,  116,  327,  269,  116,
      112,  117,  117,  117,  267,  117,  118,  118,  118,  258,
      118,  119,  119,  120,  120,  119,  342,  120,  121,  121,
      342,  119,  121,  120,  122,  122,  369,  369,  122,  123,
      123,  123,  257,  123,  124,  124,  124,  357,  124,  125,
      125,  126,  126,  125,  357,  126,  127,  127,  127,  252,

      127,  143,  143,  143,  251,  143,  127,  128,  128,  128,
      246,  128,  144,  144,  144,  245,  144,  128,  135,  135,
      358,  199,  199,  135,  135,  199,  190,  358,  135,  135,
      135,  135,  149,  149,  135,  137,  137,  137,  301,  137,
      301,  149,  189,  149,  200,  200,  150,  150,  200,  370,
      370,  137,  138,  138,  138,  150,  138,  150,  159,  159,
      159,  185,  159,  160,  160,  160,  180,  160,  138,  139,
      139,  139,  179,  139,  197,  197,  197,  164,  197,  139,
      140,  140,  140,  163,  140,  198,  198,  198,  162,  198,
      140,  141,  141,  141,  416,  141,  193,  193,  194,  194,

      193,  141,  194,  161,  243,  243,  416,  141,  145,  145,
      314,  314,  193,  243,  194,  243,  302,  145,  302,  145,
      145,  146,  146,  154,  314,  205,  205,  195,  195,  205,
      146,  195,  146,  146,  155,  155,  153,  195,  196,  196,
      201,  201,  196,  155,  201,  155,  148,  304,  196,  304,
      201,  417,  155,  156,  156,  202,  202,  206,  206,  202,
      147,  206,  156,  417,  156,  202,  207,  207,  207,  132,
      207,  156,  169,  169,  169,  131,  169,  208,  208,  208,
      350,  208,  211,  211,  350,  305,  211,  305,  169,  170,
      170,  170,  211,  170,  212,  212,  215,  215,  212,  130,

      215,  129,  331,  331,  212,  170,  171,  171,  171,  419,
      171,  216,  216,  217,  217,  216,  331,  217,  332,  332,
       61,  419,  171,  172,  172,  172,   56,  172,  332,  217,
      218,  218,  237,  237,  218,   55,  237,   40,  397,  172,
      173,  173,  173,   39,  173,  397,  218,  221,  221,  221,
      173,  221,   38,  244,  244,   37,  173,  175,  175,  222,
      222,  222,  244,  222,  244,  415,  175,   30,  175,  223,
      223,  223,  415,  223,   29,  175,  176,  176,  224,  224,
      224,   24,  224,  359,  359,  176,   23,  176,  359,  225,
      225,  253,  253,  225,  176,  177,  177,  229,  229,  229,

      253,  229,  253,  360,  177,  225,  177,  360,  227,  227,
      254,  254,  227,  177,  178,  178,  230,  230,  230,  254,
      230,  254,    8,  178,  227,  178,  228,  228,    7,    6,
      228,  388,  178,  181,  181,  181,    5,  181,  388,  284,
      284,  284,  228,  233,  233,  284,  388,  233,    0,  181,
      182,  182,  182,  233,  182,  234,  234,  238,  238,  234,
        0,  238,    0,  338,  338,  234,  182,  187,  187,  247,
      247,  247,    0,  247,  392,  392,  187,  338,  187,  248,
      248,  248,    0,  248,  392,  187,  188,  188,  188,    0,
      188,  249,  249,  249,    0,  249,  250,  250,  250,    0,

      250,    0,  188,  191,  191,  273,  273,  273,    0,  288,
      288,  288,  191,    0,  191,  288,  354,  354,  291,  273,
      291,  191,  192,  192,  291,  322,  292,  322,  292,  322,
      354,  192,  292,  192,  322,  326,  326,  393,  393,  326,
      192,  203,  203,  203,  294,  203,  294,  393,    0,    0,
      294,  203,  204,  204,  204,  296,  204,  296,    0,  356,
      356,  296,  204,  209,  209,  209,  303,  209,  303,  306,
      362,  306,  303,  356,  362,  306,  339,  339,  339,  209,
      210,  210,  210,  307,  210,  307,  308,  363,  308,  307,
      339,  363,  308,    0,    0,    0,  210,  213,  213,  213,

      310,  213,  310,  312,    0,  312,  310,  213,  323,  312,
      323,    0,  323,  213,  219,  219,  219,  323,  219,  341,
      341,  341,    0,    0,  219,  220,  220,  220,    0,  220,
      345,    0,  345,  341,  345,  220,  226,  226,  226,  345,
      226,  324,  324,    0,    0,  324,  226,  231,  231,  324,
        0,  231,  325,  325,  347,  347,  325,  231,  347,    0,
      325,    0,  347,  231,  232,  232,  365,  346,  232,  346,
      365,  346,  364,  364,  232,  367,  346,  364,    0,  367,
      232,  235,  235,  235,    0,  235,  348,  348,  349,  349,
      348,  368,  349,    0,  348,  368,    0,  235,  236,  236,

      236,    0,  236,  361,  361,  361,  366,  366,  366,  361,
        0,    0,  366,    0,  236,  239,  239,  239,  371,  239,
      373,  372,  371,  372,  373,  239,  383,  372,    0,    0,
      383,  239,  241,  241,  241,  374,  241,  374,  382,  382,
      384,  374,  382,  385,  384,    0,  382,  385,  241,  242,
      242,  242,  386,  242,  387,    0,  386,    0,  387,  242,
      390,  389,    0,    0,  390,  242,  260,  260,  260,  403,
      260,  260,  389,  403,  391,  391,  389,    0,  402,  402,
      260,  263,  402,  263,  263,  263,  402,  263,  391,    0,
      263,  263,  263,  265,  265,  265,    0,  265,    0,  265,

      398,  398,  398,  404,  265,  266,  405,  404,  266,  266,
      405,  406,  266,  407,  398,  406,  266,  407,  410,    0,
      266,  274,  410,  274,  274,  274,    0,  274,    0,    0,
      274,  274,  274,  276,  276,  276,  408,  276,    0,  276,
      399,  399,  399,  408,  276,  277,  422,    0,  277,  277,
      422,  408,  277,    0,  399,    0,  277,  400,  400,  400,
      277,  315,  315,  315,    0,  315,  315,    0,  401,  401,
      401,  400,  409,    0,    0,  315,  318,  318,  318,    0,
      318,  318,  401,  409,  413,  413,    0,  409,  423,  430,
      318,  328,  423,  430,  328,  328,  424,  424,  413,    0,

      431,  424,  426,  426,  431,    0,  328,  428,  428,  428,
      424,    0,    0,  328,  334,  334,  426,    0,  334,  334,
      438,  428,  432,  432,  438,    0,    0,  432,  334,  351,
      434,  434,  351,  351,  434,    0,  432,  439,  434,  436,
      436,  439,  440,  436,  351,  441,  440,  436,    0,  441,
      439,  351,  377,  377,  377,    0,  377,  377,  441,    0,
        0,    0,    0,    0,    0,    0,  377,  378,  378,  378,
        0,  378,  378,    0,    0,    0,    0,    0,    0,    0,
        0,  378,  381,  381,  381,    0,  381,  381,    0,    0,
        0,    0,    0,    0,    0,    0,  381,  395,  395,    0,

        0,  395,  395,    0,    0,    0,    0,    0,    0,    0,
        0,  395,  446,  446,  446,  447,  447,  448,    0,  448,
      449,    0,  449,  450,  450,  450,  451,  451,  451,  452,
        0,  452,  453,  453,  453,  454,  454,  454,  456,    0,
      456,  457,  457,  457,  458,  458,  458,  459,    0,  459,
      460,  460,  460,  461,  461,  461,  462,  462,  462,  463,
      463,  463,  464,  464,  464,  465,    0,  465,  466,    0,
      466,  467,  467,  467,  468,    0,  468,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,

      444,  444,  444,  444,  444
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET

	#define BACH_MAX
	#ifdef BACH_MAX
    #include "llllobj.h"
    #include "ext_common.h"
    #include "ext_globalsymbol.h"
    #include "strparser.h"
    #else
    #include <stdio.h>
    #include <ctype.h>
    #define parserpost printf
    #endif
    
    #include "bach_strparser_tab.h"
    #define YY_DECL int yylex \
            (YYSTYPE *yylval_param, yyscan_t yyscanner)
            
    t_symbol *gensym_unescape(const char *txt);

    #define YY_NO_UNISTD_H

#define INITIAL 0
#define NO_L 1
#define NO_b 2
#define NO_Lb 3
#define NO_e 4
#define NO_Le 5
#define NO_be 6
#define NO_Lbe 7
#define NO_l 8
#define NO_Ll 9
#define NO_bl 10
#define NO_Lbl 11
#define NO_el 12
#define NO_Lel 13
#define NO_bel 14
#define NO_Lbel 15
#define NO_p 16
#define NO_Lp 17
#define NO_bp 18
#define NO_Lbp 19
#define NO_ep 20
#define NO_Lep 21
#define NO_bep 22
#define NO_Lbep 23
#define NO_lp 24
#define NO_Llp 25
#define NO_blp 26
#define NO_Lblp 27
#define NO_elp 28
#define NO_Lelp 29
#define NO_belp 30
#define NO_Lbelp 31
#define NO_r 32
#define NO_Lr 33
#define NO_br 34
#define NO_Lbr 35
#define NO_er 36
#define NO_Ler 37
#define NO_ber 38
#define NO_Lber 39
#define NO_lr 40
#define NO_Llr 41
#define NO_blr 42
#define NO_Lblr 43
#define NO_elr 44
#define NO_Lelr 45
#define NO_belr 46
#define NO_Lbelr 47
#define NO_pr 48
#define NO_Lpr 49
#define NO_bpr 50
#define NO_Lbpr 51
#define NO_epr 52
#define NO_Lepr 53
#define NO_bepr 54
#define NO_Lbepr 55
#define NO_lpr 56
#define NO_Llpr 57
#define NO_blpr 58
#define NO_Lblpr 59
#define NO_elpr 60
#define NO_Lelpr 61
#define NO_belpr 62
#define NO_Lbelpr 63
#define NO_s 64
#define NO_Ls 65
#define NO_bs 66
#define NO_Lbs 67
#define NO_es 68
#define NO_Les 69
#define NO_bes 70
#define NO_Lbes 71
#define NO_ls 72
#define NO_Lls 73
#define NO_bls 74
#define NO_Lbls 75
#define NO_els 76
#define NO_Lels 77
#define NO_bels 78
#define NO_Lbels 79
#define NO_ps 80
#define NO_Lps 81
#define NO_bps 82
#define NO_Lbps 83
#define NO_eps 84
#define NO_Leps 85
#define NO_beps 86
#define NO_Lbeps 87
#define NO_lps 88
#define NO_Llps 89
#define NO_blps 90
#define NO_Lblps 91
#define NO_elps 92
#define NO_Lelps 93
#define NO_belps 94
#define NO_Lbelps 95
#define NO_rs 96
#define NO_Lrs 97
#define NO_brs 98
#define NO_Lbrs 99
#define NO_ers 100
#define NO_Lers 101
#define NO_bers 102
#define NO_Lbers 103
#define NO_lrs 104
#define NO_Llrs 105
#define NO_blrs 106
#define NO_Lblrs 107
#define NO_elrs 108
#define NO_Lelrs 109
#define NO_belrs 110
#define NO_Lbelrs 111
#define NO_prs 112
#define NO_Lprs 113
#define NO_bprs 114
#define NO_Lbprs 115
#define NO_eprs 116
#define NO_Leprs 117
#define NO_beprs 118
#define NO_Lbeprs 119
#define NO_lprs 120
#define NO_Llprs 121
#define NO_blprs 122
#define NO_Lblprs 123
#define NO_elprs 124
#define NO_Lelprs 125
#define NO_belprs 126
#define NO_Lbelprs 127

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

YYSTYPE * yyget_lval ( yyscan_t yyscanner );

void yyset_lval ( YYSTYPE * yylval_param , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  , yyscan_t yyscanner);
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 445 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 444 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
{
        parserpost(" lex: BACH_PUSH\n");
        return BACH_PUSH;
    }
	YY_BREAK
case 2:
YY_RULE_SETUP
{
        parserpost(" lex: BACH_POP\n");
        return BACH_POP;
    }
	YY_BREAK

case 3:
YY_RULE_SETUP
{
    parserpost(" lex: INTEGER %d\n", atoi(yytext));
    yylval->l = atol(yytext);
    return BACH_LONG;
}
	YY_BREAK

case 4:
YY_RULE_SETUP
{
        yylval->r = t_parser::eatRational(yytext);
        parserpost(" lex: RATIONAL %ld / %ld\n", yylval->r.num(), yylval->r.den());
        return BACH_RAT;
    }
	YY_BREAK

case 5:
YY_RULE_SETUP
{
        yylval->d = atof(yytext);
        parserpost(" lex: BACH_DOUBLE %lf\n", yylval->d);
        return BACH_DOUBLE;
    }
	YY_BREAK

case 6:
YY_RULE_SETUP
{
        yylval->d = atof(yytext);
        parserpost(" lex: BACH_DOUBLE %lf\n", yylval->d);
        return BACH_DOUBLE;
    }
	YY_BREAK

case 7:
YY_RULE_SETUP
{
        yylval->p = t_parser::eatPitchAsNameAccInt(yytext);
        parserpost(" lex: NOTE: degree %ld, alter %ld/%ld, octave %ld\n", yylval->p.degree(), yylval->p.alter().num(), yylval->p.alter().den(), yylval->p.octave());
        return BACH_PITCH;
    }
	YY_BREAK
case 8:
YY_RULE_SETUP
{
        yylval->p = t_parser::eatPitchAsNameIntAcc(yytext);
        parserpost(" lex: NOTE: degree %ld, alter %ld/%ld, octave %ld\n", yylval->p.degree(), yylval->p.alter().num(), yylval->p.alter().den(), yylval->p.octave());
        return BACH_PITCH;
    }
	YY_BREAK
case 9:
YY_RULE_SETUP
{
        yylval->p = t_parser::eatPitchAsNameAccIntIntT(yytext);
        parserpost(" lex: NOTE: degree %ld, alter %ld/%ld, octave %ld\n", yylval->p.degree(), yylval->p.alter().num(), yylval->p.alter().den(), yylval->p.octave());
        return BACH_PITCH;
    }
	YY_BREAK
case 10:
YY_RULE_SETUP
{
        yylval->p = t_parser::eatPitchAsNameAccIntRatT(yytext);
        parserpost(" lex: NOTE: degree %ld, alter %ld/%ld, octave %ld\n", yylval->p.degree(), yylval->p.alter().num(), yylval->p.alter().den(), yylval->p.octave());
        return BACH_PITCH;
    }
	YY_BREAK

case 11:
YY_RULE_SETUP
{
        parserpost(" lex: BACKTICKED BACH_SYMBOL %s\n", yytext + 1);
        yylval->sym = gensym(yytext + 1);
        return BACH_SYMBOL;
    }
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
{
        parserpost(" lex: BACKTICKED BACH_SYMBOL %s\n", yytext + 1);
        yylval->sym = gensym_unescape(yytext + 1);
        return BACH_SYMBOL;
    }
	YY_BREAK

case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
{
    parserpost(" lex: QUOTED BACH_SYMBOL %s\n", yytext);
    *(yytext + yyleng - 1) = 0;
    yylval->sym = gensym(yytext + 1);
    *(yytext + yyleng - 1) = '"';
    return BACH_SYMBOL;
}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
{
    parserpost(" lex: QUOTED BACH_SYMBOL %s\n", yytext);
    *(yytext + yyleng - 1) = 0;
    yylval->sym = gensym_unescape(yytext + 1);
    *(yytext + yyleng - 1) = '"';
    return BACH_SYMBOL;
}
	YY_BREAK

case 15:
YY_RULE_SETUP
{
        parserpost(" lex: null\n");
        return BACH_NULL;
    }
	YY_BREAK
case 16:
YY_RULE_SETUP
{
        parserpost(" lex: nil\n");
        return BACH_NIL;
    }
	YY_BREAK

case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
{
	parserpost(" lex: Whitespace\n");
}
	YY_BREAK

case 18:
YY_RULE_SETUP
{
        parserpost(" lex: BACH_SYMBOL %s\n", yytext);
        yylval->sym = gensym(yytext);
        return BACH_SYMBOL;
    }
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
{
        parserpost(" lex: BACH_SYMBOL %s\n", yytext);
        yylval->sym = gensym_unescape(yytext);
        return BACH_SYMBOL;
    }
	YY_BREAK

case 20:
YY_RULE_SETUP
{
        parserpost(" lex: BACH_SYMBOL %s\n", yytext);
        yylval->sym = gensym(yytext);
        return BACH_SYMBOL;
    }
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
{
        parserpost(" lex: BACH_SYMBOL %s\n", yytext);
        yylval->sym = gensym_unescape(yytext);
        return BACH_SYMBOL;
    }
	YY_BREAK

case 22:
YY_RULE_SETUP
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(NO_L):
case YY_STATE_EOF(NO_b):
case YY_STATE_EOF(NO_Lb):
case YY_STATE_EOF(NO_e):
case YY_STATE_EOF(NO_Le):
case YY_STATE_EOF(NO_be):
case YY_STATE_EOF(NO_Lbe):
case YY_STATE_EOF(NO_l):
case YY_STATE_EOF(NO_Ll):
case YY_STATE_EOF(NO_bl):
case YY_STATE_EOF(NO_Lbl):
case YY_STATE_EOF(NO_el):
case YY_STATE_EOF(NO_Lel):
case YY_STATE_EOF(NO_bel):
case YY_STATE_EOF(NO_Lbel):
case YY_STATE_EOF(NO_p):
case YY_STATE_EOF(NO_Lp):
case YY_STATE_EOF(NO_bp):
case YY_STATE_EOF(NO_Lbp):
case YY_STATE_EOF(NO_ep):
case YY_STATE_EOF(NO_Lep):
case YY_STATE_EOF(NO_bep):
case YY_STATE_EOF(NO_Lbep):
case YY_STATE_EOF(NO_lp):
case YY_STATE_EOF(NO_Llp):
case YY_STATE_EOF(NO_blp):
case YY_STATE_EOF(NO_Lblp):
case YY_STATE_EOF(NO_elp):
case YY_STATE_EOF(NO_Lelp):
case YY_STATE_EOF(NO_belp):
case YY_STATE_EOF(NO_Lbelp):
case YY_STATE_EOF(NO_r):
case YY_STATE_EOF(NO_Lr):
case YY_STATE_EOF(NO_br):
case YY_STATE_EOF(NO_Lbr):
case YY_STATE_EOF(NO_er):
case YY_STATE_EOF(NO_Ler):
case YY_STATE_EOF(NO_ber):
case YY_STATE_EOF(NO_Lber):
case YY_STATE_EOF(NO_lr):
case YY_STATE_EOF(NO_Llr):
case YY_STATE_EOF(NO_blr):
case YY_STATE_EOF(NO_Lblr):
case YY_STATE_EOF(NO_elr):
case YY_STATE_EOF(NO_Lelr):
case YY_STATE_EOF(NO_belr):
case YY_STATE_EOF(NO_Lbelr):
case YY_STATE_EOF(NO_pr):
case YY_STATE_EOF(NO_Lpr):
case YY_STATE_EOF(NO_bpr):
case YY_STATE_EOF(NO_Lbpr):
case YY_STATE_EOF(NO_epr):
case YY_STATE_EOF(NO_Lepr):
case YY_STATE_EOF(NO_bepr):
case YY_STATE_EOF(NO_Lbepr):
case YY_STATE_EOF(NO_lpr):
case YY_STATE_EOF(NO_Llpr):
case YY_STATE_EOF(NO_blpr):
case YY_STATE_EOF(NO_Lblpr):
case YY_STATE_EOF(NO_elpr):
case YY_STATE_EOF(NO_Lelpr):
case YY_STATE_EOF(NO_belpr):
case YY_STATE_EOF(NO_Lbelpr):
case YY_STATE_EOF(NO_s):
case YY_STATE_EOF(NO_Ls):
case YY_STATE_EOF(NO_bs):
case YY_STATE_EOF(NO_Lbs):
case YY_STATE_EOF(NO_es):
case YY_STATE_EOF(NO_Les):
case YY_STATE_EOF(NO_bes):
case YY_STATE_EOF(NO_Lbes):
case YY_STATE_EOF(NO_ls):
case YY_STATE_EOF(NO_Lls):
case YY_STATE_EOF(NO_bls):
case YY_STATE_EOF(NO_Lbls):
case YY_STATE_EOF(NO_els):
case YY_STATE_EOF(NO_Lels):
case YY_STATE_EOF(NO_bels):
case YY_STATE_EOF(NO_Lbels):
case YY_STATE_EOF(NO_ps):
case YY_STATE_EOF(NO_Lps):
case YY_STATE_EOF(NO_bps):
case YY_STATE_EOF(NO_Lbps):
case YY_STATE_EOF(NO_eps):
case YY_STATE_EOF(NO_Leps):
case YY_STATE_EOF(NO_beps):
case YY_STATE_EOF(NO_Lbeps):
case YY_STATE_EOF(NO_lps):
case YY_STATE_EOF(NO_Llps):
case YY_STATE_EOF(NO_blps):
case YY_STATE_EOF(NO_Lblps):
case YY_STATE_EOF(NO_elps):
case YY_STATE_EOF(NO_Lelps):
case YY_STATE_EOF(NO_belps):
case YY_STATE_EOF(NO_Lbelps):
case YY_STATE_EOF(NO_rs):
case YY_STATE_EOF(NO_Lrs):
case YY_STATE_EOF(NO_brs):
case YY_STATE_EOF(NO_Lbrs):
case YY_STATE_EOF(NO_ers):
case YY_STATE_EOF(NO_Lers):
case YY_STATE_EOF(NO_bers):
case YY_STATE_EOF(NO_Lbers):
case YY_STATE_EOF(NO_lrs):
case YY_STATE_EOF(NO_Llrs):
case YY_STATE_EOF(NO_blrs):
case YY_STATE_EOF(NO_Lblrs):
case YY_STATE_EOF(NO_elrs):
case YY_STATE_EOF(NO_Lelrs):
case YY_STATE_EOF(NO_belrs):
case YY_STATE_EOF(NO_Lbelrs):
case YY_STATE_EOF(NO_prs):
case YY_STATE_EOF(NO_Lprs):
case YY_STATE_EOF(NO_bprs):
case YY_STATE_EOF(NO_Lbprs):
case YY_STATE_EOF(NO_eprs):
case YY_STATE_EOF(NO_Leprs):
case YY_STATE_EOF(NO_beprs):
case YY_STATE_EOF(NO_Lbeprs):
case YY_STATE_EOF(NO_lprs):
case YY_STATE_EOF(NO_Llprs):
case YY_STATE_EOF(NO_blprs):
case YY_STATE_EOF(NO_Lblprs):
case YY_STATE_EOF(NO_elprs):
case YY_STATE_EOF(NO_Lelprs):
case YY_STATE_EOF(NO_belprs):
case YY_STATE_EOF(NO_Lbelprs):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 445 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 445 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 444);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp , yyscan_t yyscanner)
{
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = yyg->yy_n_chars + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

#define YYTABLES_NAME "yytables"

#ifndef BACH_MAX
int main(int argc, char **argv)
{
	yylex();
}
#endif

t_strParser::t_strParser(t_bool bigString, long ignore) : t_parser()
{
    if (!bigString) {
        setPtr(sizeof(struct yyguts_t));
        setBasePtr();
        reset();
    }
    big = bigString; 
    startCondition = ignore;
}

void t_strParser::reset()
{
    t_parser::reset();
    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(this,0x00,sizeof(struct yyguts_t));
    //yy_init_globals ((yyscan_t) this);
}

YY_BUFFER_STATE strparser_scan_string(yyscan_t myscanner, const char *buf)
{
    struct yyguts_t *yyg = (struct yyguts_t*) myscanner;
    BEGIN ((t_strParser *) myscanner)->getStartCondition();
    YY_BUFFER_STATE bp = strparser__scan_string(buf,myscanner);
    strparser__switch_to_buffer(bp,myscanner);
    return bp;
}

void strparser_flush_and_delete_buffer(yyscan_t myscanner, YY_BUFFER_STATE bp)
{
    yy_flush_buffer(bp, myscanner);
    yy_delete_buffer(bp, myscanner);
}

t_symbol *gensym_unescape(const char *txt)
{
    char name[MAX_SYM_LENGTH];
    char *this_name = name;
    long count = 0;
    t_bool justescaped = false;
    while (*txt && count < MAX_SYM_LENGTH - 1) {
        if (*txt == '\\' && !justescaped) {
            txt++;
            justescaped = true;
        } else {
            *(this_name++) = *(txt++);
            count++;
            justescaped = false;
        }
    }
    *this_name = 0;
    return gensym(name);
}

void *strparser_alloc(size_t bytes, void *yyscanner)
{
    void *b;
    if (!yyscanner) {
        b = bach_newptr(sizeof(t_strParser)); // it's much more than we actually need, but this lets us define a valid "big" field
    } else if (((t_strParser *) yyscanner)->isBig()) {
        b = bach_newptr(bytes);
    } else {
        b = ((t_strParser *) yyscanner)->getPtr(bytes);
    }
    parserpost(" strparser_alloc: %d bytes requested, returning %p", bytes, b);
    return b;
}

void *strparser_realloc(void *ptr, size_t bytes, void *yyscanner)
{
    if (((t_strParser *) yyscanner)->isBig()) {
        void *b = bach_resizeptr(ptr, bytes);
        parserpost(" strparser_realloc: %d bytes requested for pointer %p, returning %p", bytes, ptr, b);
        return b;
    } else {
        parserpost(" strparser_realloc: %d bytes requested for pointer %p, returning %p", bytes, ptr, ptr);
        return ptr;
    }
}

void strparser_free(void *ptr,void *yyscanner)
{
    if (((t_strParser *) yyscanner)->isBig()) {
        parserpost(" strparser_free: freeing %p", ptr);
        bach_freeptr(ptr);
    } else {
        parserpost(" strparser_free: requested to free %ptr but doing nothing", ptr);
    }
    
}

