/*
 *  bach_accidentals.hpp
 *
 * Copyright (C) 2010-2022 Andrea Agostini and Daniele Ghisi
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License
 * as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 *
 */

#ifndef bach_accidentals_hpp
#define bach_accidentals_hpp

//#include <string>
//#include <vector>
#include "math/rational.h"


/** Accidental preferences.
    @ingroup    accidentals
 */
typedef enum _accidentals_preferences {
    k_ACC_AUTO = 0,    ///< Automatic choice of accidentals
    k_ACC_SHARPS,    ///< Prefer the use of sharps
    k_ACC_FLATS,    ///< Prefer the use of flats
    k_ACC_CUSTOM,    ///< Accidental are explicitely defined via the "enharmonictable" attribute, and thus the t_notation_obj::full_acc_repr symbol
} e_accidentals_preferences;



typedef enum {
    BACH_ACCIDENTAL_NONE = 0,
    // equal-tempered accidentals
    BACH_ACCIDENTAL_DOUBLEFLAT_ARROW_DOWN = 1,
    BACH_ACCIDENTAL_DOUBLEFLAT = 2,
    BACH_ACCIDENTAL_DOUBLEFLAT_ARROW_UP = 3,
    BACH_ACCIDENTAL_THREEQUARTERFLAT_ARROW_DOWN = 4,
    BACH_ACCIDENTAL_THREEQUARTERFLAT = 5,
    BACH_ACCIDENTAL_THREEQUARTERFLAT_ARROW_UP = 6,
    BACH_ACCIDENTAL_FLAT_ARROW_DOWN = 7,
    BACH_ACCIDENTAL_FLAT = 8,
    BACH_ACCIDENTAL_FLAT_ARROW_UP = 9,
    BACH_ACCIDENTAL_QUARTERFLAT_ARROW_DOWN = 10,
    BACH_ACCIDENTAL_QUARTERFLAT = 11,
    BACH_ACCIDENTAL_QUARTERFLAT_ARROW_UP = 12,
    BACH_ACCIDENTAL_NATURAL_ARROW_DOWN = 13,
    BACH_ACCIDENTAL_NATURAL = 14,
    BACH_ACCIDENTAL_NATURAL_ARROW_UP = 15,
    BACH_ACCIDENTAL_QUARTERSHARP_ARROW_DOWN = 16,
    BACH_ACCIDENTAL_QUARTERSHARP = 17,
    BACH_ACCIDENTAL_QUARTERSHARP_ARROW_UP = 18,
    BACH_ACCIDENTAL_SHARP_ARROW_DOWN = 19,
    BACH_ACCIDENTAL_SHARP = 20,
    BACH_ACCIDENTAL_SHARP_ARROW_UP = 21,
    BACH_ACCIDENTAL_THREEQUARTERSHARP_ARROW_DOWN = 22,
    BACH_ACCIDENTAL_THREEQUARTERSHARP = 23,
    BACH_ACCIDENTAL_THREEQUARTERSHARP_ARROW_UP = 24,
    BACH_ACCIDENTAL_DOUBLESHARP_ARROW_DOWN = 25,
    BACH_ACCIDENTAL_DOUBLESHARP = 26,
    BACH_ACCIDENTAL_DOUBLESHARP_ARROW_UP = 27,
    
    // just intonation accidentals (HEJI ver.2)
    BACH_ACCIDENTAL_JI_DOUBLEFLAT = 28,
    BACH_ACCIDENTAL_JI_FLAT = 29,
    BACH_ACCIDENTAL_JI_NATURAL = 30,
    BACH_ACCIDENTAL_JI_SHARP = 31,
    BACH_ACCIDENTAL_JI_DOUBLESHARP = 32,
    BACH_ACCIDENTAL_JI_DOUBLEFLAT_ARROW_UP = 33,
    BACH_ACCIDENTAL_JI_FLAT_ARROW_UP = 34,
    BACH_ACCIDENTAL_JI_NATURAL_ARROW_UP = 35,
    BACH_ACCIDENTAL_JI_SHARP_ARROW_UP = 36,
    BACH_ACCIDENTAL_JI_DOUBLESHARP_ARROW_UP = 37,
    BACH_ACCIDENTAL_JI_DOUBLEFLAT_ARROW_DOWN = 38,
    BACH_ACCIDENTAL_JI_FLAT_ARROW_DOWN = 39,
    BACH_ACCIDENTAL_JI_NATURAL_ARROW_DOWN = 40,
    BACH_ACCIDENTAL_JI_SHARP_ARROW_DOWN = 41,
    BACH_ACCIDENTAL_JI_DOUBLESHARP_ARROW_DOWN = 42,
    BACH_ACCIDENTAL_JI_DOUBLEFLAT_ARROW_UP_TWICE = 43,
    BACH_ACCIDENTAL_JI_FLAT_ARROW_UP_TWICE = 44,
    BACH_ACCIDENTAL_JI_NATURAL_ARROW_UP_TWICE = 45,
    BACH_ACCIDENTAL_JI_SHARP_ARROW_UP_TWICE = 46,
    BACH_ACCIDENTAL_JI_DOUBLESHARP_ARROW_UP_TWICE = 47,
    BACH_ACCIDENTAL_JI_DOUBLEFLAT_ARROW_DOWN_TWICE = 48,
    BACH_ACCIDENTAL_JI_FLAT_ARROW_DOWN_TWICE = 49,
    BACH_ACCIDENTAL_JI_NATURAL_ARROW_DOWN_TWICE = 50,
    BACH_ACCIDENTAL_JI_SHARP_ARROW_DOWN_TWICE = 51,
    BACH_ACCIDENTAL_JI_DOUBLESHARP_ARROW_DOWN_TWICE = 52,
    BACH_ACCIDENTAL_JI_DOUBLEFLAT_ARROW_UP_THRICE = 53,
    BACH_ACCIDENTAL_JI_FLAT_ARROW_UP_THRICE = 54,
    BACH_ACCIDENTAL_JI_NATURAL_ARROW_UP_THRICE = 55,
    BACH_ACCIDENTAL_JI_SHARP_ARROW_UP_THRICE = 56,
    BACH_ACCIDENTAL_JI_DOUBLESHARP_ARROW_UP_THRICE = 57,
    BACH_ACCIDENTAL_JI_DOUBLEFLAT_ARROW_DOWN_THRICE = 58,
    BACH_ACCIDENTAL_JI_FLAT_ARROW_DOWN_THRICE = 59,
    BACH_ACCIDENTAL_JI_NATURAL_ARROW_DOWN_THRICE = 60,
    BACH_ACCIDENTAL_JI_SHARP_ARROW_DOWN_THRICE = 61,
    BACH_ACCIDENTAL_JI_DOUBLESHARP_ARROW_DOWN_THRICE = 62,
    BACH_ACCIDENTAL_JI_COMMA_7_UP = 63,
    BACH_ACCIDENTAL_JI_COMMA_7_DOWN = 64,
    BACH_ACCIDENTAL_JI_COMMA_7_UP_TWICE = 65,
    BACH_ACCIDENTAL_JI_COMMA_7_DOWN_TWICE = 66,
    BACH_ACCIDENTAL_JI_COMMA_11_UP = 67,
    BACH_ACCIDENTAL_JI_COMMA_11_DOWN = 68,
    BACH_ACCIDENTAL_JI_COMMA_13_UP = 69,
    BACH_ACCIDENTAL_JI_COMMA_13_DOWN = 70,
    BACH_ACCIDENTAL_JI_COMMA_17_UP = 71,
    BACH_ACCIDENTAL_JI_COMMA_17_DOWN = 72,
    BACH_ACCIDENTAL_JI_COMMA_19_UP = 73,
    BACH_ACCIDENTAL_JI_COMMA_19_DOWN = 74,
    BACH_ACCIDENTAL_JI_COMMA_23_UP = 75,
    BACH_ACCIDENTAL_JI_COMMA_23_DOWN = 76,
    BACH_ACCIDENTAL_JI_COMMA_29_UP = 77,
    BACH_ACCIDENTAL_JI_COMMA_29_DOWN = 78,
    BACH_ACCIDENTAL_JI_COMMA_31_UP = 79,
    BACH_ACCIDENTAL_JI_COMMA_31_DOWN = 80,
    BACH_ACCIDENTAL_JI_COMMA_37_UP = 81,
    BACH_ACCIDENTAL_JI_COMMA_37_DOWN = 82,
    BACH_ACCIDENTAL_JI_COMMA_41_UP = 83,
    BACH_ACCIDENTAL_JI_COMMA_41_DOWN = 84,
    BACH_ACCIDENTAL_JI_COMMA_43_UP = 85,
    BACH_ACCIDENTAL_JI_COMMA_43_DOWN = 86,
    BACH_ACCIDENTAL_JI_COMMA_47_UP = 87,
    BACH_ACCIDENTAL_JI_COMMA_47_DOWN = 88,
    
    //TODO: ADD ET ONES
    BACH_ACCIDENTAL_JI_DOUBLEFLAT_ET = 89,
    BACH_ACCIDENTAL_JI_FLAT_ET = 90,
    BACH_ACCIDENTAL_JI_NATURAL_ET = 91,
    BACH_ACCIDENTAL_JI_SHARP_ET = 92,
    BACH_ACCIDENTAL_JI_DOUBLESHARP_ET = 93,
    BACH_ACCIDENTAL_JI_QUARTERSHARP_ET = 94,
    BACH_ACCIDENTAL_JI_QUARTERFLAT_ET = 95,

    BACH_ACCIDENTAL_BOGUS = 96,
} e_bach_accidental;

#define BACH_NUM_ACCIDENTALS 97





#endif /* bach_pitch_hpp */
