

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE symparser_restart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via symparser_restart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void symparser_restart (FILE *input_file ,yyscan_t yyscanner );
void symparser__switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE symparser__create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void symparser__delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void symparser__flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void symparser_push_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void symparser_pop_buffer_state (yyscan_t yyscanner );

static void symparser_ensure_buffer_stack (yyscan_t yyscanner );
static void symparser__load_buffer_state (yyscan_t yyscanner );
static void symparser__init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER symparser__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE symparser__scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE symparser__scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE symparser__scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *symparser_alloc (yy_size_t ,yyscan_t yyscanner );
void *symparser_realloc (void *,yy_size_t ,yyscan_t yyscanner );
void symparser_free (void * ,yyscan_t yyscanner );

#define yy_new_buffer symparser__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        symparser_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            symparser__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        symparser_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            symparser__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define symparser_wrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 18
#define YY_END_OF_BUFFER 19
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[396] =
    {   0,
       15,   15,   17,   17,   15,   15,   17,   17,   15,   15,
       17,   17,   15,   15,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   15,   15,   17,   17,   15,   15,   17,   17,
       15,   15,   17,   17,   15,   15,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   15,   15,   17,   17,   15,   15,
       17,   17,   15,   15,   17,   17,   15,   15,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   15,   15,   17,   17,

       15,   15,   17,   17,   15,   15,   17,   17,   15,   15,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   15,   15,
       17,   17,   15,   15,   17,   17,   15,   15,   17,   17,
       15,   15,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       15,   15,   17,   17,   15,   15,   17,   17,   15,   15,
       17,   17,   15,   15,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   15,   15,   17,   17,   15,   15,   17,   17,

       15,   15,   17,   17,   15,   15,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   15,   15,   17,   17,   15,   15,
       17,   17,   15,   15,   17,   17,   15,   15,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   19,   15,   15,   15,
        1,    2,   15,   15,    3,   15,   11,   15,   17,   18,
       17,   17,   17,    3,   17,   11,   17,   15,   15,    3,
       17,   17,    3,    1,    2,   15,   17,   15,   17,   15,
        3,   17,    3,   15,    3,   17,    3,   15,   17,   15,

       17,   15,   15,    0,   15,   15,   16,   12,   16,   15,
        3,   15,    5,    5,   15,   15,   15,   15,    7,   11,
       11,   11,   15,   15,   17,   12,   17,    3,   17,    5,
        5,   17,   17,   17,   17,    7,   11,   17,   17,   15,
        3,    6,    6,   17,    3,    6,    6,    3,    3,    3,
        3,   15,   15,    4,   15,    5,   15,    7,    8,   15,
       11,   11,   11,   14,   15,   17,   17,    4,   17,    5,
       17,    7,    8,   17,   14,   17,   15,    5,   15,   13,
       17,    5,   17,   13,   15,    9,   17,    9,   15,   15,
       17,   17,   10,   10,    0

    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    6,
        7,    1,    8,    2,    8,    9,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,    2,    1,
        1,    1,    1,    1,   12,   12,   12,   12,   13,   12,
       12,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    1,   14,   15,   16,   15,   16,

       17,   15,   15,    1,   18,    1,    1,   19,    1,   20,
        1,    1,    5,    1,    1,   21,   22,    5,    1,    5,
        1,    1,    1,   23,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[24] =
    {   0,
        1,    1,    2,    1,    1,    3,    3,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[407] =
    {   0,
        0,    0,   23,    0,  912,  911,  906,  905,   39,   43,
       47,   51,   55,   62,   69,   76,   61,   68,    0,    0,
       75,   85,  904,  903,   94,    0,   87,   89,  900,  899,
      100,  102,  109,    0,  119,    0,  898,  897,  895,  894,
      102,  129,  133,  137,  141,  148,  155,  162,   91,  112,
        0,    0,  147,  161,  892,  891,  171,    0,  122,  177,
      888,  887,  179,  181,  104,  112,  122,  181,  183,  188,
      197,    0,  201,  205,  209,  213,  217,  224,  228,  232,
      238,  240,  886,  884,  194,  223,    0,    0,  240,  242,
      247,  251,  253,  255,  262,  266,  257,  268,  270,  272,

      274,  276,  278,  283,  287,  291,  295,  299,  303,  310,
      317,  324,  328,  332,  305,  312,  336,  343,  345,  347,
      319,  338,  354,  358,  360,  362,  369,  376,  871,  863,
      858,  383,  295,  328,  361,  378,  396,  409,  386,  422,
      435,    0,  448,  461,  389,  393,  474,  843,  489,  504,
      403,  368,  841,  837,  517,    0,  388,  401,  842,  840,
      829,  821,  816,  805,  405,  408,  412,  420,  530,  543,
      430,  432,  556,    0,  571,  586,  441,  447,  804,  788,
      601,  616,  421,  431,  777,  744,  456,  458,  446,  457,
      631,  646,  472,  478,  459,  470,  491,  496,  720,  678,

      505,  506,  416,  504,  519,  521,  532,  534,  661,  676,
      473,  477,  515,  527,  644,  613,  548,  549,  547,  563,
      689,  702,  572,  573,  590,  591,  605,  606,  564,  586,
      715,  728,  620,  621,  741,  754,  571,  601,  767,    0,
      780,  793,  635,  636,  806,    0,  468,  555,  650,  651,
      582,  552,  582,  597,    0,    0,  553,  825,  666,  831,
      616,  637,  835,   61,  849,  863,  878,  670,    0, 1098,
      545,  877,  533,  886,  899,    0,   31,   77,  147,  912,
      163,  525,  639,    0,    0,  497,  401,  675,  654,  512,
      631,  447,  666,  669,  690,  676,  680,  703,  684,  716,

      693,  397,  712,  703,  725,    0,    0,  368,    0,  223,
        0,    0,  920,  934,  616,  713,  646,  238,  947,  969,
      727,  735,  253,  360,    0,    0,  349,    0,  972,  730,
      740,  700,  747,  984,  323,  996,    0,  286,  282,  318,
     1016,  755,  756,  282,  735,  212,  208,  758,  760,  768,
      745,  782,  769,  781,  792,  794,  795, 1024,  778,  805,
      804,    0,    0,  211,  586,  810,  196,  187,  179,  170,
      154,  832,  779,  149,    0,  128,  808,  818, 1044,  139,
      128,   93,  854,    0,  865,   75,  834,    0,  819,  866,
       50,  861,   53,    0, 1098, 1065, 1068, 1071, 1074, 1077,

     1080, 1083, 1085, 1088, 1091, 1094
    } ;

static yyconst flex_int16_t yy_def[407] =
    {   0,
      395,    1,  395,    3,    1,    1,    3,    3,    1,    1,
        3,    3,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,   25,   25,   25,   25,   25,
       25,   25,    1,   33,    3,   35,   33,   33,   35,   35,
       33,   33,   35,   35,   33,   33,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   57,   57,   57,
       57,   57,   57,   57,    1,    1,    3,    3,    1,    1,
       25,   71,    1,    1,    3,    3,    1,    1,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   25,   25,
        3,    3,   25,   25,   71,   71,   33,   33,   35,   35,

       33,   33,   35,   35,   33,   33,   35,   35,   33,   33,
       35,   35,   57,   57,   35,   35,   57,   57,   35,   35,
       57,   57,   35,   35,   57,   57,   35,   35,    1,    1,
        3,   71,    1,    1,    3,   71,    1,    1,   25,    3,
        1,  141,   71,   71,    3,    3,   71,    3,    3,    3,
       71,    3,   25,   25,   71,  155,   25,   25,  155,  155,
       33,   33,   35,   35,   33,   33,   35,   35,   33,   33,
       57,   57,   33,  173,   57,   57,   35,   35,   35,   35,
       35,   35,   35,   35,   57,   57,   57,   57,   57,   57,
       57,   57,    1,    1,   71,   71,  141,  141,   71,   71,

      141,  141,  155,  155,  141,  141,  155,  155,   71,   71,
       71,   71,   71,   71,   71,   71,   25,   25,  155,  155,
       25,   25,  155,  155,   33,   33,   35,   35,  173,  173,
       35,   35,  173,  173,   35,   35,  173,  173,   35,  239,
       57,   57,   35,   35,   57,  245,  245,  245,   57,   57,
      239,  239,  239,  239,  239,  239,  395,  396,  397,  396,
      398,  398,  260,  260,  260,  260,  399,  260,  400,  395,
      400,  400,  400,  400,  400,  401,  400,  263,  260,  260,
      272,  400,  400,  400,  400,  260,  400,  260,  400,  263,
      265,  272,  274,  263,  260,  272,  400,  260,  400,  260,

      400,  260,  397,  398,  397,  402,  403,  260,  403,  260,
      265,  266,  260,  260,  260,  260,  266,  260,  266,  399,
      404,  405,  260,  260,  400,  400,  400,  274,  400,  400,
      400,  400,  400,  400,  400,  400,  401,  400,  400,  260,
      260,  260,  260,  400,  400,  400,  400,  265,  274,  260,
      400,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      404,  406,  406,  260,  260,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  260,  260,  260,  260,
      400,  400,  400,  400,  260,  260,  400,  400,  260,  260,
      400,  400,  260,  400,    0,  395,  395,  395,  395,  395,

      395,  395,  395,  395,  395,  395
    } ;

static yyconst flex_uint16_t yy_nxt[1122] =
    {   0,
      258,  259,  259,  260,  258,  261,  262,  263,  264,  258,
      265,  266,  266,  267,  266,  266,  266,  258,  258,  268,
      258,  258,  258,  269,  269,  270,  271,  269,  269,  269,
      272,  273,  269,  274,  275,  275,  276,  275,  275,  275,
      269,  269,  277,  269,  269,  269,  278,  279,  338,  280,
      278,  279,  339,  280,  281,  282,  302,  283,  281,  282,
      392,  283,  278,  279,  302,  280,  284,  285,  258,  278,
      279,  313,  280,  284,  285,  258,  281,  282,  302,  283,
      284,  285,  269,  281,  282,  340,  283,  341,  269,  269,
      284,  285,  269,  269,  269,  269,  284,  285,  269,  284,

      285,  281,  282,  382,  283,  269,  269,  269,  269,  288,
      279,  290,  280,  269,  291,  269,  286,  284,  285,  290,
      258,  258,  291,  258,  258,  258,  287,  269,  269,  292,
      269,  269,  293,  269,  269,  269,  288,  279,  382,  280,
      289,  282,  302,  283,  289,  282,  384,  283,  288,  279,
      302,  280,  284,  285,  258,  288,  279,  342,  280,  383,
      269,  258,  289,  282,  372,  283,  284,  285,  269,  289,
      282,  344,  283,  345,  269,  269,  284,  285,  289,  282,
      370,  283,  269,  269,  269,  269,  269,  269,  292,  370,
      290,  293,  269,  291,  269,  290,  258,  368,  291,  284,

      285,  258,  269,  269,  292,  273,  368,  293,  294,  279,
      269,  295,  294,  279,  302,  295,  296,  282,  346,  297,
      296,  282,  346,  297,  294,  279,  302,  295,  284,  285,
      258,  294,  279,  313,  295,  296,  282,  258,  297,  296,
      282,  302,  297,  284,  285,  284,  285,  296,  319,  296,
      297,  276,  297,  276,  296,  282,  302,  297,  296,  282,
      296,  297,  296,  297,  298,  297,  269,  291,  269,  296,
      282,  364,  297,  296,  282,  298,  297,  299,  291,  299,
      293,  298,  293,  298,  291,  299,  291,  258,  293,  258,
      299,  269,  346,  293,  300,  279,  269,  295,  300,  279,

      376,  295,  301,  282,  375,  297,  301,  282,  258,  297,
      300,  279,  299,  295,  258,  293,  258,  300,  279,  299,
      295,  302,  293,  258,  301,  282,  301,  297,  342,  297,
      269,  301,  282,  336,  297,  299,  273,  269,  293,  299,
      273,  258,  293,  299,  273,  301,  293,  258,  297,  269,
      299,  273,  299,  293,  299,  293,  269,  293,  269,  330,
      269,  301,  282,  302,  297,  301,  282,  301,  297,  301,
      297,  302,  297,  269,  269,  269,  301,  282,  365,  297,
      269,  269,  269,  301,  282,  272,  297,  269,  274,  269,
      272,  269,  269,  274,  284,  285,  276,  269,  284,  285,

      302,  269,  269,  278,  279,  269,  280,  269,  269,  327,
      272,  328,  269,  274,  269,  258,  278,  279,  258,  280,
      269,  258,  269,  296,  258,  269,  297,  258,  258,  281,
      282,  269,  283,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  278,  279,  269,  280,  284,  285,  258,  269,
      269,  269,  284,  285,  258,  281,  282,  349,  283,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  281,  282,
      269,  283,  276,  269,  269,  269,  269,  269,  269,  290,
      269,  272,  291,  276,  274,  290,  276,  276,  291,  269,
      276,  258,  269,  269,  284,  285,  269,  258,  290,  264,

      302,  291,  269,  290,  264,  310,  291,  311,  269,  284,
      285,  296,  294,  294,  297,  295,  295,  269,  267,  267,
      284,  285,  348,  269,  281,  282,  294,  283,  294,  295,
      276,  295,  284,  285,  269,  346,  269,  288,  279,  296,
      280,  296,  297,  330,  297,  269,  269,  269,  326,  258,
      288,  279,  395,  280,  296,  296,  296,  297,  297,  297,
      269,  269,  258,  288,  279,  276,  280,  269,  269,  258,
      296,  298,  264,  297,  291,  258,  269,  269,  300,  296,
      296,  295,  297,  297,  269,  269,  269,  284,  285,  302,
      269,  269,  269,  298,  264,  276,  291,  298,  298,  269,

      291,  291,  284,  285,  380,  269,  284,  285,  300,  258,
      258,  295,  299,  299,  269,  293,  293,  309,  309,  302,
      269,  284,  285,  353,  269,  269,  354,  300,  300,  269,
      295,  295,  269,  267,  267,  269,  269,  269,  309,  309,
      302,  348,  299,  299,  269,  293,  293,  347,  332,  345,
      269,  269,  269,  357,  269,  269,  358,  301,  301,  269,
      297,  297,  344,  269,  345,  269,  284,  285,  306,  269,
      269,  307,  307,  302,  276,  325,  349,  340,  302,  350,
      269,  284,  285,  340,  344,  341,  351,  323,  347,  276,
      351,  324,  327,  302,  349,  269,  296,  269,  343,  297,

      350,  344,  269,  351,  309,  309,  302,  367,  269,  296,
      368,  310,  297,  348,  306,  269,  302,  307,  307,  302,
      355,  269,  299,  356,  340,  293,  350,  306,  269,  306,
      307,  307,  362,  362,  269,  299,  363,  309,  293,  269,
      330,  269,  366,  347,  332,  345,  366,  269,  301,  282,
      330,  297,  366,  347,  369,  351,  366,  370,  302,  302,
      269,  301,  282,  269,  297,  342,  342,  302,  348,  325,
      349,  302,  302,  269,  301,  282,  343,  297,  350,  354,
      269,  302,  359,  373,  302,  302,  269,  299,  273,  377,
      293,  354,  378,  359,  373,  302,  269,  302,  302,  269,

      299,  273,  356,  293,  356,  358,  306,  269,  302,  362,
      362,  302,  269,  299,  273,  379,  293,  381,  378,  269,
      382,  302,  302,  269,  269,  269,  303,  303,  378,  390,
      304,  304,  303,  303,  308,  269,  304,  304,  302,  374,
      258,  391,  372,  310,  392,  311,  312,  312,  258,  312,
      312,  312,  302,  269,  374,  269,  269,  314,  315,  311,
      269,  316,  269,  387,  383,  316,  302,  317,  302,  302,
      318,  392,  389,  319,  388,  390,  390,  269,  317,  321,
      303,  394,  258,  322,  322,  327,  393,  328,  329,  329,
      258,  329,  329,  329,  331,  332,  328,  276,  333,  276,

      269,  269,  333,  334,  269,  269,  335,  269,  269,  336,
      258,  258,  269,  269,  334,  302,  269,  269,  269,  269,
      343,  315,  341,  302,  258,  258,  395,  395,  395,  395,
      313,  395,  352,  395,  395,  395,  352,  302,  395,  395,
      395,  395,  395,  395,  313,  395,  352,  395,  395,  395,
      352,  359,  395,  395,  360,  395,  395,  395,  395,  395,
      395,  395,  359,  395,  395,  395,  395,  395,  395,  360,
      321,  303,  395,  395,  322,  322,  334,  395,  395,  335,
      395,  395,  336,  395,  395,  395,  395,  334,  334,  395,
      395,  371,  395,  395,  372,  395,  395,  395,  395,  334,

      373,  395,  395,  374,  395,  395,  336,  395,  395,  395,
      395,  373,  395,  395,  395,  395,  395,  395,  374,  302,
      395,  395,  395,  395,  343,  315,  341,  302,  395,  395,
      395,  360,  395,  395,  358,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  360,  302,  395,  395,
      395,  395,  395,  385,  379,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  386,  302,  302,  302,  305,  305,
      305,  304,  304,  304,  320,  320,  320,  325,  395,  325,
      337,  395,  337,  306,  306,  307,  395,  307,  361,  361,
      361,  322,  322,  322,  362,  395,  362,  257,  395,  395,

      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395
    } ;

static yyconst flex_int16_t yy_chk[1122] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    9,    9,  277,    9,
       10,   10,  277,   10,   11,   11,  393,   11,   12,   12,
      391,   12,   13,   13,  264,   13,   17,   17,   13,   14,
       14,  264,   14,   18,   18,   14,   15,   15,  386,   15,
       21,   21,   15,   16,   16,  278,   16,  278,   21,   16,
       22,   22,   27,   27,   28,   28,   49,   49,   22,   25,

       25,   25,   25,  382,   25,   31,   31,   32,   32,   41,
       41,   65,   41,   31,   65,   32,   33,   50,   50,   66,
       33,   33,   66,   33,   33,   33,   35,   59,   59,   67,
       35,   35,   67,   35,   35,   35,   42,   42,  381,   42,
       43,   43,  380,   43,   44,   44,  376,   44,   45,   45,
      279,   45,   53,   53,   45,   46,   46,  279,   46,  374,
       53,   46,   47,   47,  371,   47,   54,   54,   47,   48,
       48,  281,   48,  281,   54,   48,   57,   57,   57,   57,
      370,   57,   60,   60,   63,   63,   64,   64,   68,  369,
       69,   68,   63,   69,   64,   70,   69,  368,   70,   85,

       85,   70,   71,   71,   71,   71,  367,   71,   73,   73,
       71,   73,   74,   74,  364,   74,   75,   75,  347,   75,
       76,   76,  346,   76,   77,   77,  310,   77,   86,   86,
       77,   78,   78,  310,   78,   79,   79,   78,   79,   80,
       80,  318,   80,   81,   81,   82,   82,   89,  318,   90,
       89,   81,   90,   82,   91,   91,  323,   91,   92,   92,
       93,   92,   94,   93,   97,   94,   93,   97,   94,   95,
       95,  323,   95,   96,   96,   98,   96,   99,   98,  100,
       99,  101,  100,  102,  101,  103,  102,  101,  103,  102,
      104,  103,  344,  104,  105,  105,  104,  105,  106,  106,

      339,  106,  107,  107,  338,  107,  108,  108,  133,  108,
      109,  109,  115,  109,  133,  115,  109,  110,  110,  116,
      110,  340,  116,  110,  111,  111,  121,  111,  340,  121,
      111,  112,  112,  335,  112,  113,  113,  112,  113,  114,
      114,  134,  114,  117,  117,  122,  117,  134,  122,  117,
      118,  118,  119,  118,  120,  119,  118,  120,  119,  327,
      120,  123,  123,  324,  123,  124,  124,  125,  124,  126,
      125,  308,  126,  125,  135,  126,  127,  127,  324,  127,
      135,  152,  127,  128,  128,  136,  128,  152,  136,  128,
      132,  139,  139,  132,  145,  145,  132,  136,  146,  146,

      302,  157,  132,  137,  137,  139,  137,  157,  145,  287,
      151,  287,  146,  151,  158,  137,  138,  138,  165,  138,
      158,  166,  151,  203,  165,  167,  203,  166,  138,  140,
      140,  167,  140,  168,  183,  171,  171,  172,  172,  168,
      183,  140,  141,  141,  184,  141,  177,  177,  141,  171,
      184,  172,  178,  178,  141,  143,  143,  292,  143,  189,
      177,  187,  187,  188,  188,  189,  178,  143,  144,  144,
      190,  144,  195,  247,  247,  187,  190,  188,  195,  193,
      144,  147,  193,  196,  147,  194,  211,  147,  194,  196,
      212,  193,  211,  147,  149,  149,  212,  194,  197,  197,

      286,  197,  149,  198,  198,  286,  198,  286,  149,  150,
      150,  204,  201,  202,  204,  201,  202,  150,  201,  202,
      213,  213,  290,  150,  155,  155,  205,  155,  206,  205,
      155,  206,  214,  214,  213,  282,  155,  169,  169,  207,
      169,  208,  207,  273,  208,  207,  214,  208,  271,  169,
      170,  170,  257,  170,  219,  217,  218,  219,  217,  218,
      248,  248,  170,  173,  173,  252,  173,  217,  218,  173,
      220,  229,  229,  220,  229,  173,  175,  175,  237,  223,
      224,  237,  223,  224,  175,  223,  224,  253,  253,  365,
      175,  176,  176,  230,  230,  251,  230,  225,  226,  176,

      225,  226,  254,  254,  365,  176,  181,  181,  238,  225,
      226,  238,  227,  228,  181,  227,  228,  261,  261,  315,
      181,  182,  182,  315,  227,  228,  315,  233,  234,  182,
      233,  234,  216,  233,  234,  182,  191,  191,  262,  262,
      291,  291,  243,  244,  191,  243,  244,  283,  283,  283,
      191,  192,  192,  317,  243,  244,  317,  249,  250,  192,
      249,  250,  289,  215,  289,  192,  209,  209,  259,  249,
      250,  259,  259,  268,  209,  293,  293,  294,  288,  294,
      209,  210,  210,  288,  296,  288,  296,  268,  297,  210,
      297,  268,  299,  295,  299,  210,  221,  200,  295,  221,

      295,  301,  221,  301,  304,  304,  298,  332,  221,  222,
      332,  298,  222,  298,  303,  222,  316,  303,  303,  300,
      316,  222,  231,  316,  300,  231,  300,  305,  231,  321,
      305,  305,  321,  321,  231,  232,  322,  322,  232,  199,
      330,  232,  330,  345,  345,  345,  330,  232,  235,  235,
      331,  235,  331,  351,  333,  351,  331,  333,  342,  343,
      235,  236,  236,  186,  236,  342,  343,  348,  348,  349,
      349,  350,  353,  236,  239,  239,  350,  239,  350,  353,
      239,  359,  359,  373,  354,  352,  239,  241,  241,  352,
      241,  354,  352,  359,  373,  355,  185,  356,  357,  241,

      242,  242,  355,  242,  356,  357,  361,  180,  360,  361,
      361,  377,  242,  245,  245,  360,  245,  366,  377,  245,
      366,  378,  389,  179,  164,  245,  258,  258,  378,  389,
      258,  258,  260,  260,  260,  163,  260,  260,  263,  372,
      162,  387,  372,  263,  387,  263,  263,  263,  161,  263,
      263,  263,  265,  160,  372,  159,  154,  265,  265,  265,
      153,  265,  148,  383,  383,  265,  266,  266,  385,  390,
      266,  392,  385,  266,  383,  385,  390,  131,  266,  267,
      267,  392,  130,  267,  267,  272,  390,  272,  272,  272,
      129,  272,  272,  272,  274,  274,  274,   84,  274,   83,

       62,   61,  274,  275,   56,   55,  275,   40,   39,  275,
       38,   37,   30,   29,  275,  280,   24,   23,    8,    7,
      280,  280,  280,  313,    6,    5,    0,    0,    0,    0,
      313,    0,  313,    0,    0,    0,  313,  314,    0,    0,
        0,    0,    0,    0,  314,    0,  314,    0,    0,    0,
      314,  319,    0,    0,  319,    0,    0,    0,    0,    0,
        0,    0,  319,    0,    0,    0,    0,    0,    0,  319,
      320,  320,    0,    0,  320,  320,  329,    0,    0,  329,
        0,    0,  329,    0,    0,    0,    0,  329,  334,    0,
        0,  334,    0,    0,  334,    0,    0,    0,    0,  334,

      336,    0,    0,  336,    0,    0,  336,    0,    0,    0,
        0,  336,    0,    0,    0,    0,    0,    0,  336,  341,
        0,    0,    0,    0,  341,  341,  341,  358,    0,    0,
        0,  358,    0,    0,  358,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  358,  379,    0,    0,
        0,    0,    0,  379,  379,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  379,  396,  396,  396,  397,  397,
      397,  398,  398,  398,  399,  399,  399,  400,    0,  400,
      401,    0,  401,  402,  402,  403,    0,  403,  404,  404,
      404,  405,  405,  405,  406,    0,  406,  395,  395,  395,

      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET

    #define BACH_MAX
    #ifdef BACH_MAX
    #include "llllobj.h"
    #include "ext_common.h"
    #include "ext_globalsymbol.h"
    #include "symparser.h"
    #else
    #include <stdio.h>
    #include <ctype.h>
    #define parserpost printf
    #endif
    
    #include "bach_symparser_tab.h"
    #define YY_DECL int symparser_lex(YYSTYPE *yylval_param,yyscan_t yyscanner)
    
#define INITIAL 0
#define NO_L 1
#define NO_b 2
#define NO_Lb 3
#define NO_e 4
#define NO_Le 5
#define NO_be 6
#define NO_Lbe 7
#define NO_l 8
#define NO_Ll 9
#define NO_bl 10
#define NO_Lbl 11
#define NO_el 12
#define NO_Lel 13
#define NO_bel 14
#define NO_Lbel 15
#define NO_p 16
#define NO_Lp 17
#define NO_bp 18
#define NO_Lbp 19
#define NO_ep 20
#define NO_Lep 21
#define NO_bep 22
#define NO_Lbep 23
#define NO_lp 24
#define NO_Llp 25
#define NO_blp 26
#define NO_Lblp 27
#define NO_elp 28
#define NO_Lelp 29
#define NO_belp 30
#define NO_Lbelp 31
#define NO_r 32
#define NO_Lr 33
#define NO_br 34
#define NO_Lbr 35
#define NO_er 36
#define NO_Ler 37
#define NO_ber 38
#define NO_Lber 39
#define NO_lr 40
#define NO_Llr 41
#define NO_blr 42
#define NO_Lblr 43
#define NO_elr 44
#define NO_Lelr 45
#define NO_belr 46
#define NO_Lbelr 47
#define NO_pr 48
#define NO_Lpr 49
#define NO_bpr 50
#define NO_Lbpr 51
#define NO_epr 52
#define NO_Lepr 53
#define NO_bepr 54
#define NO_Lbepr 55
#define NO_lpr 56
#define NO_Llpr 57
#define NO_blpr 58
#define NO_Lblpr 59
#define NO_elpr 60
#define NO_Lelpr 61
#define NO_belpr 62
#define NO_Lbelpr 63
#define NO_s 64
#define NO_Ls 65
#define NO_bs 66
#define NO_Lbs 67
#define NO_es 68
#define NO_Les 69
#define NO_bes 70
#define NO_Lbes 71
#define NO_ls 72
#define NO_Lls 73
#define NO_bls 74
#define NO_Lbls 75
#define NO_els 76
#define NO_Lels 77
#define NO_bels 78
#define NO_Lbels 79
#define NO_ps 80
#define NO_Lps 81
#define NO_bps 82
#define NO_Lbps 83
#define NO_eps 84
#define NO_Leps 85
#define NO_beps 86
#define NO_Lbeps 87
#define NO_lps 88
#define NO_Llps 89
#define NO_blps 90
#define NO_Lblps 91
#define NO_elps 92
#define NO_Lelps 93
#define NO_belps 94
#define NO_Lbelps 95
#define NO_rs 96
#define NO_Lrs 97
#define NO_brs 98
#define NO_Lbrs 99
#define NO_ers 100
#define NO_Lers 101
#define NO_bers 102
#define NO_Lbers 103
#define NO_lrs 104
#define NO_Llrs 105
#define NO_blrs 106
#define NO_Lblrs 107
#define NO_elrs 108
#define NO_Lelrs 109
#define NO_belrs 110
#define NO_Lbelrs 111
#define NO_prs 112
#define NO_Lprs 113
#define NO_bprs 114
#define NO_Lbprs 115
#define NO_eprs 116
#define NO_Leprs 117
#define NO_beprs 118
#define NO_Lbeprs 119
#define NO_lprs 120
#define NO_Llprs 121
#define NO_blprs 122
#define NO_Lblprs 123
#define NO_elprs 124
#define NO_Lelprs 125
#define NO_belprs 126
#define NO_Lbelprs 127

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    yy_size_t yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int symparser_lex_init (yyscan_t* scanner);

int symparser_lex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int symparser_lex_destroy (yyscan_t yyscanner );

int symparser_get_debug (yyscan_t yyscanner );

void symparser_set_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE symparser_get_extra (yyscan_t yyscanner );

void symparser_set_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *symparser_get_in (yyscan_t yyscanner );

void symparser_set_in  (FILE * _in_str ,yyscan_t yyscanner );

FILE *symparser_get_out (yyscan_t yyscanner );

void symparser_set_out  (FILE * _out_str ,yyscan_t yyscanner );

yy_size_t symparser_get_leng (yyscan_t yyscanner );

char *symparser_get_text (yyscan_t yyscanner );

int symparser_get_lineno (yyscan_t yyscanner );

void symparser_set_lineno (int _line_number ,yyscan_t yyscanner );

int symparser_get_column  (yyscan_t yyscanner );

void symparser_set_column (int _column_no ,yyscan_t yyscanner );

YYSTYPE * symparser_get_lval (yyscan_t yyscanner );

void symparser_set_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int symparser_wrap (yyscan_t yyscanner );
#else
extern int symparser_wrap (yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int symparser_lex \
               (YYSTYPE * yylval_param ,yyscan_t yyscanner);

#define YY_DECL int symparser_lex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			symparser_ensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				symparser__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		symparser__load_buffer_state(yyscanner );
		}

	{

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 396 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1098 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
{
        parserpost(" lex: PUSH\n");
        return PUSH;
    }
	YY_BREAK
case 2:
YY_RULE_SETUP
{
        parserpost(" lex: POPPE\n");
        return POP;
    }
	YY_BREAK

case 3:
YY_RULE_SETUP
{
    parserpost(" lex: INTEGER %d\n", atoi(yytext));
    yylval->l = atol(yytext);
    return LONG;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
{
    yylval->r = t_parser::eatRational(yytext);
    parserpost(" lex: RATIONAL %ld / %ld\n", yylval->r.num(), yylval->r.den());
    return RAT;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
{
    yylval->d = atof(yytext);
    parserpost(" lex: DOUBLE %lf\n", yylval->d);
    return DOUBLE;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
{
    yylval->d = atof(yytext);
    parserpost(" lex: DOUBLE %lf\n", yylval->d);
    return DOUBLE;
}
	YY_BREAK

case 7:
YY_RULE_SETUP
{
        yylval->p = t_parser::eatPitchAsNameAccInt(yytext);
        parserpost(" lex: NOTE: degree %ld, alter %ld/%ld, octave %ld\n", yylval->p.degree(), yylval->p.alter().num(), yylval->p.alter().den(), yylval->p.octave());
        return PITCH;
    }
	YY_BREAK
case 8:
YY_RULE_SETUP
{
        yylval->p = t_parser::eatPitchAsNameIntAcc(yytext);
        parserpost(" lex: NOTE: degree %ld, alter %ld/%ld, octave %ld\n", yylval->p.degree(), yylval->p.alter().num(), yylval->p.alter().den(), yylval->p.octave());
        return PITCH;
    }
	YY_BREAK
case 9:
YY_RULE_SETUP
{
        yylval->p = t_parser::eatPitchAsNameAccIntIntT(yytext);
        parserpost(" lex: NOTE: degree %ld, alter %ld/%ld, octave %ld\n", yylval->p.degree(), yylval->p.alter().num(), yylval->p.alter().den(), yylval->p.octave());
        return PITCH;
    }
	YY_BREAK
case 10:
YY_RULE_SETUP
{
        yylval->p = t_parser::eatPitchAsNameAccIntRatT(yytext);
        parserpost(" lex: NOTE: degree %ld, alter %ld/%ld, octave %ld\n", yylval->p.degree(), yylval->p.alter().num(), yylval->p.alter().den(), yylval->p.octave());
        return PITCH;
    }
	YY_BREAK

case 11:
YY_RULE_SETUP
{
    parserpost(" lex: BACKTICKED SYMBOL %s\n", yytext + 1);
    yylval->sym = gensym(yytext + 1);
    return SYMBOL;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
{
    parserpost(" lex: QUOTED EMPTY SYMBOL %s\n", yytext);
    yylval->sym = gensym("");
    return SYMBOL;
}
	YY_BREAK

case 13:
YY_RULE_SETUP
{
        parserpost(" lex: null\n");
        return BACHNULL;
    }
	YY_BREAK
case 14:
YY_RULE_SETUP
{
        parserpost(" lex: nil\n");
        return BACHNIL;
    }
	YY_BREAK

case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
{
        parserpost(" lex: SYMBOL %s\n", yytext);
        yylval->sym = gensym(yytext);
        return SYMBOL;
    }
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
{
        parserpost(" lex: SYMBOL %s\n", yytext);
        yylval->sym = gensym(yytext);
        return SYMBOL;
    }
	YY_BREAK

case 17:
YY_RULE_SETUP
{
        parserpost(" lex: SYMBOL %s\n", yytext);
        yylval->sym = gensym(yytext);
        return SYMBOL;
    }
	YY_BREAK

case 18:
YY_RULE_SETUP
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(NO_L):
case YY_STATE_EOF(NO_b):
case YY_STATE_EOF(NO_Lb):
case YY_STATE_EOF(NO_e):
case YY_STATE_EOF(NO_Le):
case YY_STATE_EOF(NO_be):
case YY_STATE_EOF(NO_Lbe):
case YY_STATE_EOF(NO_l):
case YY_STATE_EOF(NO_Ll):
case YY_STATE_EOF(NO_bl):
case YY_STATE_EOF(NO_Lbl):
case YY_STATE_EOF(NO_el):
case YY_STATE_EOF(NO_Lel):
case YY_STATE_EOF(NO_bel):
case YY_STATE_EOF(NO_Lbel):
case YY_STATE_EOF(NO_p):
case YY_STATE_EOF(NO_Lp):
case YY_STATE_EOF(NO_bp):
case YY_STATE_EOF(NO_Lbp):
case YY_STATE_EOF(NO_ep):
case YY_STATE_EOF(NO_Lep):
case YY_STATE_EOF(NO_bep):
case YY_STATE_EOF(NO_Lbep):
case YY_STATE_EOF(NO_lp):
case YY_STATE_EOF(NO_Llp):
case YY_STATE_EOF(NO_blp):
case YY_STATE_EOF(NO_Lblp):
case YY_STATE_EOF(NO_elp):
case YY_STATE_EOF(NO_Lelp):
case YY_STATE_EOF(NO_belp):
case YY_STATE_EOF(NO_Lbelp):
case YY_STATE_EOF(NO_r):
case YY_STATE_EOF(NO_Lr):
case YY_STATE_EOF(NO_br):
case YY_STATE_EOF(NO_Lbr):
case YY_STATE_EOF(NO_er):
case YY_STATE_EOF(NO_Ler):
case YY_STATE_EOF(NO_ber):
case YY_STATE_EOF(NO_Lber):
case YY_STATE_EOF(NO_lr):
case YY_STATE_EOF(NO_Llr):
case YY_STATE_EOF(NO_blr):
case YY_STATE_EOF(NO_Lblr):
case YY_STATE_EOF(NO_elr):
case YY_STATE_EOF(NO_Lelr):
case YY_STATE_EOF(NO_belr):
case YY_STATE_EOF(NO_Lbelr):
case YY_STATE_EOF(NO_pr):
case YY_STATE_EOF(NO_Lpr):
case YY_STATE_EOF(NO_bpr):
case YY_STATE_EOF(NO_Lbpr):
case YY_STATE_EOF(NO_epr):
case YY_STATE_EOF(NO_Lepr):
case YY_STATE_EOF(NO_bepr):
case YY_STATE_EOF(NO_Lbepr):
case YY_STATE_EOF(NO_lpr):
case YY_STATE_EOF(NO_Llpr):
case YY_STATE_EOF(NO_blpr):
case YY_STATE_EOF(NO_Lblpr):
case YY_STATE_EOF(NO_elpr):
case YY_STATE_EOF(NO_Lelpr):
case YY_STATE_EOF(NO_belpr):
case YY_STATE_EOF(NO_Lbelpr):
case YY_STATE_EOF(NO_s):
case YY_STATE_EOF(NO_Ls):
case YY_STATE_EOF(NO_bs):
case YY_STATE_EOF(NO_Lbs):
case YY_STATE_EOF(NO_es):
case YY_STATE_EOF(NO_Les):
case YY_STATE_EOF(NO_bes):
case YY_STATE_EOF(NO_Lbes):
case YY_STATE_EOF(NO_ls):
case YY_STATE_EOF(NO_Lls):
case YY_STATE_EOF(NO_bls):
case YY_STATE_EOF(NO_Lbls):
case YY_STATE_EOF(NO_els):
case YY_STATE_EOF(NO_Lels):
case YY_STATE_EOF(NO_bels):
case YY_STATE_EOF(NO_Lbels):
case YY_STATE_EOF(NO_ps):
case YY_STATE_EOF(NO_Lps):
case YY_STATE_EOF(NO_bps):
case YY_STATE_EOF(NO_Lbps):
case YY_STATE_EOF(NO_eps):
case YY_STATE_EOF(NO_Leps):
case YY_STATE_EOF(NO_beps):
case YY_STATE_EOF(NO_Lbeps):
case YY_STATE_EOF(NO_lps):
case YY_STATE_EOF(NO_Llps):
case YY_STATE_EOF(NO_blps):
case YY_STATE_EOF(NO_Lblps):
case YY_STATE_EOF(NO_elps):
case YY_STATE_EOF(NO_Lelps):
case YY_STATE_EOF(NO_belps):
case YY_STATE_EOF(NO_Lbelps):
case YY_STATE_EOF(NO_rs):
case YY_STATE_EOF(NO_Lrs):
case YY_STATE_EOF(NO_brs):
case YY_STATE_EOF(NO_Lbrs):
case YY_STATE_EOF(NO_ers):
case YY_STATE_EOF(NO_Lers):
case YY_STATE_EOF(NO_bers):
case YY_STATE_EOF(NO_Lbers):
case YY_STATE_EOF(NO_lrs):
case YY_STATE_EOF(NO_Llrs):
case YY_STATE_EOF(NO_blrs):
case YY_STATE_EOF(NO_Lblrs):
case YY_STATE_EOF(NO_elrs):
case YY_STATE_EOF(NO_Lelrs):
case YY_STATE_EOF(NO_belrs):
case YY_STATE_EOF(NO_Lbelrs):
case YY_STATE_EOF(NO_prs):
case YY_STATE_EOF(NO_Lprs):
case YY_STATE_EOF(NO_bprs):
case YY_STATE_EOF(NO_Lbprs):
case YY_STATE_EOF(NO_eprs):
case YY_STATE_EOF(NO_Leprs):
case YY_STATE_EOF(NO_beprs):
case YY_STATE_EOF(NO_Lbeprs):
case YY_STATE_EOF(NO_lprs):
case YY_STATE_EOF(NO_Llprs):
case YY_STATE_EOF(NO_blprs):
case YY_STATE_EOF(NO_Lblprs):
case YY_STATE_EOF(NO_elprs):
case YY_STATE_EOF(NO_Lelprs):
case YY_STATE_EOF(NO_belprs):
case YY_STATE_EOF(NO_Lbelprs):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * symparser_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( symparser_wrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of symparser_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	yy_size_t number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					symparser_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			symparser_restart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) symparser_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 396 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 396 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 395);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp , yyscan_t yyscanner)
{
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = yyg->yy_n_chars + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					symparser_restart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( symparser_wrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void symparser_restart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        symparser_ensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            symparser__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	symparser__init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	symparser__load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void symparser__switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		symparser_pop_buffer_state();
	 *		symparser_push_buffer_state(new_buffer);
     */
	symparser_ensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	symparser__load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (symparser_wrap()) processing, but the only time this flag
	 * is looked at is after symparser_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void symparser__load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE symparser__create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) symparser_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in symparser__create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) symparser_alloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in symparser__create_buffer()" );

	b->yy_is_our_buffer = 1;

	symparser__init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with symparser__create_buffer()
 * @param yyscanner The scanner object.
 */
    void symparser__delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		symparser_free((void *) b->yy_ch_buf ,yyscanner );

	symparser_free((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a symparser_restart() or at EOF.
 */
    static void symparser__init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	symparser__flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then symparser__init_buffer was _probably_
     * called from symparser_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void symparser__flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		symparser__load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void symparser_push_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	symparser_ensure_buffer_stack(yyscanner);

	/* This block is copied from symparser__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from symparser__switch_to_buffer. */
	symparser__load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void symparser_pop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	symparser__delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		symparser__load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void symparser_ensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; // After all that talk, this was set to 1 anyways...
		yyg->yy_buffer_stack = (struct yy_buffer_state**)symparser_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in symparser_ensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)symparser_realloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in symparser_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE symparser__scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) symparser_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in symparser__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	symparser__switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to symparser_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       symparser__scan_bytes() instead.
 */
YY_BUFFER_STATE symparser__scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return symparser__scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to symparser_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE symparser__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) symparser_alloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in symparser__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = symparser__scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in symparser__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE symparser_get_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int symparser_get_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int symparser_get_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *symparser_get_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *symparser_get_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t symparser_get_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *symparser_get_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void symparser_set_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void symparser_set_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "symparser_set_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void symparser_set_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "symparser_set_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see symparser__switch_to_buffer
 */
void symparser_set_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void symparser_set_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int symparser_get_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void symparser_set_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * symparser_get_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void symparser_set_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* symparser_lex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int symparser_lex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) symparser_alloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* symparser_lex_init_extra has the same functionality as symparser_lex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to symparser_alloc in
 * the yyextra field.
 */

int symparser_lex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    symparser_set_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) symparser_alloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    symparser_set_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from symparser_lex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * symparser_lex_init()
     */
    return 0;
}

/* symparser_lex_destroy is for both reentrant and non-reentrant scanners. */
int symparser_lex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		symparser__delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		symparser_pop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	symparser_free(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        symparser_free(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * symparser_lex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    symparser_free ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

#define YYTABLES_NAME "yytables"

#ifndef BACH_MAX
int main(int argc, char **argv)
{
    symparser_lex();
}
#endif

t_symParser::t_symParser(long ignore) : t_parser()
{
    setPtr(sizeof(struct yyguts_t));
    setBasePtr();
    reset();
    startCondition = ignore;
}

void t_symParser::reset()
{
    t_parser::reset();
    memset(this,0x00,sizeof(struct yyguts_t));
    //yy_init_globals ((yyscan_t) this);
}

YY_BUFFER_STATE symparser_scan_string(yyscan_t myscanner, char *buf)
{
    struct yyguts_t *yyg = (struct yyguts_t*) myscanner;
    BEGIN ((t_symParser *) myscanner)->getStartCondition();
    YY_BUFFER_STATE bp = symparser__scan_string(buf,myscanner);
    symparser__switch_to_buffer(bp,myscanner);
    return bp;
}

void symparser_flush_and_delete_buffer(yyscan_t myscanner, YY_BUFFER_STATE bp)
{
    symparser__flush_buffer(bp,myscanner);
    symparser__delete_buffer(bp,myscanner);
}

void *symparser_alloc(size_t bytes, void *yyscanner)
{
    void *b = ((t_symParser *) yyscanner)->getPtr(bytes);
    parserpost(" symparser_alloc: %d bytes requested, returning %p", bytes, b);
    return b;
}

void *symparser_realloc(void *ptr,size_t bytes, void *yyscanner)
{
    parserpost(" symparser_realloc: %d bytes requested for pointer %p, returning %p", bytes, ptr, ptr);
    return ptr;
}

void symparser_free(void *ptr,void *yyscanner)
{
    return;
}

